### ISSUE TITLE
Backgrounds

### ISSUE THREAD

**Issue by ghost** [alekmaul/pvsneslib#10]
Since the wiki article for backgrounds is not yet finished, I am lost as to how you determine the address of the map address.

```c
bgInitTileSet(1, &pic_bg0, &pal_bg0, 0, (&pic_bg0_end - &pic_bg0), 16, BG_16COLORS, 0x4000);
bgInitMapSet(1, &map_bg0, (&map_bg0_end - &map_bg0), SC_32x32, 0x0800);

setMode(BG_MODE1, 0);
```

The background displays fine in `BG0` and `BG1`, except in `BG2`

`bg0` is converted via `gfx2snes` with the following parameters: `-gs16 -pc16 -pe0 -po16 -n -fbmp -m`

**Comment by alekmaul** [comment]
BG2 is only 4 colors, this is the reason why you can't display 16 colors. Take a look at examples regarding BGs to have some tips how to implement display of Backgrounds.
