### ISSUE TITLE
Float or Fixed Point math support?

### ISSUE THREAD

**Issue by binarycounter** [alekmaul/pvsneslib#114]
Hi, 

I am trying to use floats in my code, but every time i declare a float or double the code compiles but crashes.
I cannot find information whether pvsneslib supports floats, but if that's not the case, the compiler should probably throw an error instead of silently compiling non-working code.

Here's a test based on the hello_world example:
```
---------------------------------------------------------------------------------*/
#include <snes.h>
#include <float.h>
extern char snesfont;

//---------------------------------------------------------------------------------
int main(void) {
    // Initialize SNES 
	consoleInit();
    
    // Initialize text console with our font
	consoleInitText(0, 0, &snesfont);

	// Now Put in 16 color mode and disable Bgs except current
	setMode(BG_MODE1,0);  bgSetDisable(1);  bgSetDisable(2);

	// Draw a wonderfull text :P
	float x = 0.5;
	consoleDrawText(10,10,"Floating Point Test %f",x);

	// Wait for nothing :P
	setScreenOn();  
	
	while(1) {
		WaitForVBlank();
	}
	return 0;
}
```
If I use integer based types like short, char or byte, the code works perfectly. The crash occurs regardless of if I print the variable. I'm using the release 3.5.0.

**Comment by alekmaul** [comment]
yeah, that's right. float is not support for printing and also really not recommend for old console like SNES. 
I leave this issue open but I don't know if we will try to put a compilation error about that.

**Comment by binarycounter** [comment]
Thanks for replying so quickly! 

I agree that floats should not be used on retro hardware without a FPU. Software floats would be extremely slow, but it would be nice to have some sort of compatibility or alternative way to work with decimal numbers (maybe a library that provides fixed point support?). It would ease development of game physics, especially platformers, as they often deal with subpixel precision for movement.

**Comment by alekmaul** [comment]
yeah, I add fixed point support in the wiki todo list :)
regarding platform games, you must know that pvsneslib has a map engine who  is doing the job ;) (with fixed point of course :D )
