### ISSUE TITLE
Can't run examples

### ISSUE THREAD

**Issue by zentyk** [alekmaul/pvsneslib#115]
No examples can be compiled:

Configuration (ubuntu via WSL and build-essentials).

gcc version 12.2.0 (Debian 12.2.0-1)

the repo for ubuntu was downloaded and unziped, well configured.

![image](https://user-images.githubusercontent.com/8301647/190839789-2c66f5b9-f8ad-4db2-a9bf-09072083e545.png)

![image](https://user-images.githubusercontent.com/8301647/190839890-434f8470-9fc7-4a0a-b685-6cc8f04b82f3.png)

**Comment by RetroAntho** [comment]
The 1st issue indicate that gfx2snes is not found, the 2nd is the same for snestools. I think you missed a compilation step because both are in tools folder.
Can you follow these instructions and tell us if you still have an issue?
https://github.com/alekmaul/pvsneslib/wiki/Compiling-from-sources

**Comment by alekmaul** [comment]
Please, next time, use Discord instead of Issue, it's better and faster ;)
