### ISSUE TITLE
Pro motion Newground et gfx2snes

### ISSUE THREAD

**Issue by Monos1984** [alekmaul/pvsneslib#121]
**Bug Mineur :** 
Les images sortie par pro motion (newground) un logiciel graphique n'est pas compatible ou ne semble pas compatible avec le gfx2snes.
J'utilise ce log pour réarrangé mes palettes de couleurs car photoshop en est imcapable.

Je suis donc obligé de revenir sur totoshop et juste refaire un enregistrement sous pour que l'image puisse est convertie par le gfx.
Que cela soit du png ou bmp. (c'est bien indexer)

Voila.

**Comment by Monos1984** [comment]
[sprite_player.zip](https://github.com/alekmaul/pvsneslib/files/9943457/sprite_player.zip)

**Comment by alekmaul** [comment]
L'image est en 16 couleurs et non 256 couleurs, le problème vient de là.
Même si on utilise uniquement une palette de 16 couleurs, il faut que l'image BMP soit au format 256 couleurs
