### ISSUE TITLE
Mario sample - no jump sound

### ISSUE THREAD

**Issue by RetroAntho** [alekmaul/pvsneslib#122]
Hi,

the jump sound does not work on mario sample.

see you soon!

**Comment by alekmaul** [comment]
got it, just need time to go back on snes development

**Comment by alekmaul** [comment]
Fixed in develop branch

**Comment by alekmaul** [comment]
Last one, take a look at https://github.com/alekmaul/pvsneslib/blob/develop/snes-examples/games/likemario/LikeMario.c, you will see. I Added the sound function when jumping, that was the only bug <_< ...
