### ISSUE TITLE
Mode 7 Soucie de symbole _ et de fonction

### ISSUE THREAD

**Issue by Monos1984** [alekmaul/pvsneslib#127]
Yop, A part la fonction setMode7Rot( ) les fonctions du mode  7 ne marche pas à la compilation.
<img width=500 src="https://user-images.githubusercontent.com/16206798/209666384-123b9c01-1a1d-4256-bbc0-d562fd84e2b4.png">
<img width=500 src="https://user-images.githubusercontent.com/16206798/209666414-21246789-dabe-411e-b363-5f9b13b88c00.png">

Ce que dit RetroAntho :
Les symboles avec _ sont maintenant des objets locaux dans wla, il y en a peut etre quelques uns qui ont été raté a l’époque.

Voila.

**Comment by RetroAntho** [comment]
Hello,
i just checked setMode7Angle but i do not know is this function is still needed. By removing "_" of _m7sincos, the lib and Mode7 built correctly but does not have any effect on screen when using it.
Same behaviour with setMode7MoveForwardBack (replaced by setMode7_HdmaPerspective ?) and probably with setMode7MoveLeftRight function.
I think it can be removed from the library. @alekmaul, can you confirm if it is a bug to solve or if it is old code to clean ?
