### ISSUE TITLE
has no header

### ISSUE THREAD

**Issue by jeanahelver** [alekmaul/pvsneslib#13]
The compiler seems to ignore the snes header,
I would like to set my game to pal but it's stuck on ntsc

**Comment by alekmaul** [comment]
Yes, the hdr file took is the one with the lib.
Currently, I can't find another way than patching the rom at the end of process with the tools.
I'm using such command in my Makefile (SNTOOLS is declared in the kit and is snestools.exe)

TARGET		:=	romname

GTITLE 		:= -ht"$(TARGET)"

$(SNTOOLS) -hi! -hS! $(GTITLE) -hc03 $(TARGET).sfc

**Comment by jeanahelver** [comment]
ok i added the -hc option though 03 is unknown region and ends up as NTSC
setting it to -hc01 sets it to PAL with the region ending up as italy for some reason (thats kinda wierd, but atleast its running at 50hz now 👍 )

**Comment by alekmaul** [comment]
strange, I will check the tool because it should work ...
