### ISSUE TITLE
Fonts get shifted up four rows under certain circumstances

### ISSUE THREAD

**Issue by mbh21** [alekmaul/pvsneslib#130]
Fonts seem to be getting messed up in a few different scenarios. Here are two examples.

**Method 1:**

When using objlnitEngine(); text gets messed up. When I comment out objlnitEngine() everything gets printed correctly.

In looking at this in more detail the following seems to be true:

1. columns 0 through 22 are not affected
2. The problem only exists when there exist characters in columns (X) >= 23
3. The problem only exists when Row (Y) = 2, 6, 10, 14, 18, 22, 26, or 30
4. When Row(Y) is any of the values in point 3 above, then any characters in columns >=23 get shifted 4 rows up.
5. Example: consoleDrawText(0, 14, "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"); The first 23 characters will print at
0:14 to 22:14. The last 9 characters will print at Y-4 (i.e. 23:10 to 31:10).

**Steps to reproduce:**

1. Open the hello_world.c example
2. Add the line objInitEngine(); directly after the consoleInit(); line
3. recompile and the problem exists

**Method 2:**

1. Commenting out objInitEngine (this is opposite from the above method where objInitEngine needs to be enabled)
2. Adding mapVblank() function

Then the following is true:

1. columns 0 through 5 are not affected
2. The problem only exists when there exist characters in columns (X) >= 6
3. The problem only exists when Row (Y) = 0, 4, 8, 12, 16, 20, 24, 28
4. When Row(Y) is any of the values in point 3 above, then character 6 disappears. Any characters in columns >=7 get shifted 4 rows up.
5. Example: consoleDrawText(0, 8, "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"); The first 6 characters will print at
0:8 to 5:8. The 6th character will disappear. The last 25 characters will print at Y-4 (i.e. 7:4 to 31:4).

**Steps to reproduce:**

1. Open the hello_world.c example
2. Add the line mapVblank(); directly after the WaitForVBlank(); line
3. Change the second parameter of the consoleDrawText functions to be a multiple of 4 (example: 8, 12, 16)
4. recompile and the problem exists

**Note:**
1. In Method 1, you must have the objInitEngine() function in your code in order to see the bug
2. In Method 2, you must not have the objInitEngine() function in your code in order to see the bug

**Comment by alekmaul** [comment]
MapEngine is not compatible with text drawing as it uses the same background.
So don't use mapEngine and consoletext drawing at the same time.
I still need to look deeper in 1st comment.
Also, I resized the images, too hard to read comments with default size

**Comment by alekmaul** [comment]
it was hard this one ;)
