### ISSUE TITLE
entrgy typo

### ISSUE THREAD

**Issue by jeffythedragonslayer** [alekmaul/pvsneslib#131]
"map entrgy" under Detailed Description

http://www.portabledev.com/pvsneslib/doc/a00584.html

**Comment by alekmaul** [comment]
Thanks, I will fix that ;)

**Comment by alekmaul** [comment]
got it ;) thanks !

**Comment by RetroAntho** [comment]
I solved it in this commit : https://github.com/alekmaul/pvsneslib/commit/0aad635d1735069e93ba0173945916cdb33d8a4e
we can close the issue. Thanks !
