### ISSUE TITLE
"sprite" or "OBJ" instead of "OAM"

### ISSUE THREAD

**Issue by jeffythedragonslayer** [alekmaul/pvsneslib#132]
Can we use the term "sprite" or "OBJ" instead of "oam" in some places?  I thought "OAM" referred to the entire object attribute memory, not just a single slot of that memory.

For example, in http://www.portabledev.com/pvsneslib/doc/a00596.html#a35a0da9852240ef41b5030ed21b6eeb2, I think:

> Hide or not a oam. 

would sound better as:

> Hide or show a sprite.

**Comment by alekmaul** [comment]
you're right, I will fix that

**Comment by RetroAntho** [comment]
Solved in this commit (develop branch for now) : https://github.com/alekmaul/pvsneslib/commit/0aad635d1735069e93ba0173945916cdb33d8a4e
Thank you
