### ISSUE TITLE
broken FPS counter

### ISSUE THREAD

**Issue by jeffythedragonslayer** [alekmaul/pvsneslib#136]
This line of timer.c is broken:

`        consoleDrawText(10, 10, "FPS=%d", snes_vblank_count);`

Because snes_vblank_count is the number of vblanks since consoleInit was called, not the number of vblanks per second.  It continues to climb and climb.

**Comment by mbh21** [comment]
I don't think it's broken. It's supposed to be a timer. So `FPS` may be better written as `Counter=`. With that said, %u will work better than %d because snes_blank_count is an unsigned integer. With %d, half way through at about the 32767 mark, the numbers become negative.
