### ISSUE TITLE
tiles.png already 256 colors

### ISSUE THREAD

**Issue by jeffythedragonslayer** [alekmaul/pvsneslib#138]
So I was following this tutorial: https://github.com/alekmaul/pvsneslib/wiki/Import-maps-for-Tiled

> Use your graphic editor software to change color depth of tiles to 256 colors without alpha channel (or gfx2snes will not work...).

When I opened tiles.png in Graphics Gale and then went to All Frames->Color Depth, the 8bpp (256 Colors) was already selected.  So maybe we can remove this step of the tutorial?  I don't see a checkbox to enable/disable to alpha channel.

**Comment by alekmaul** [comment]
No, I think it is important to check and validate that it is really 256 colors

**Comment by alekmaul** [comment]
yep, good point. I update the wiki
