### ISSUE TITLE
missing save step in tutorial

### ISSUE THREAD

**Issue by jeffythedragonslayer** [alekmaul/pvsneslib#139]
I think this tutorial is missing a step to save the tiled.tmx#tiles tab:

https://github.com/alekmaul/pvsneslib/wiki/Update-Maps-in-Tiled

The screenshot immediately below "Export map in jSON format" does not show the asterisk in that tab so I know it has been saved.

If you don't save it before tabbing back to the tiled.tmx tab to export you will get an "Unsaved Changes" program modal msgbox when you quit Tiled.

**Comment by alekmaul** [comment]
I think it is ok with that sentence : 
"Then, choose File/Export and save the file in json format. Name the file tiled.tmj (Type is JSON map files(*.tmj *.json)). Next time, Tiled will not ask you about a filename as you previously saved your file in json format."
