### ISSUE TITLE
Broken # FAQ hyperlinks

### ISSUE THREAD

**Issue by jeffythedragonslayer** [alekmaul/pvsneslib#140]
None of the # hyperlinks on this page work for me:

https://github.com/alekmaul/pvsneslib/wiki/Community-FAQ

**Comment by alekmaul** [comment]
That's right, we need to check why it is no more available :O !

**Comment by RetroAntho** [comment]
Hi,
Thanks to mbh21 who did the review and provided us the sources to update it, the issue is now solved !
