### ISSUE TITLE
tilestand/tileabove typo?

### ISSUE THREAD

**Issue by jeffythedragonslayer** [alekmaul/pvsneslib#142]
What is this word?  And I think there is supposed to be a space in between "tile" and "above."

> update **tilestand**, tileabove

http://www.portabledev.com/pvsneslib/doc/a00578.html#a7b24f15ef5ef84efb8f31ddb7ba22c99

**Comment by alekmaul** [comment]
I will check. I also need to do a global review of all doxygen documentation to be sure everything is ok

**Comment by alekmaul** [comment]
pvsneslib doc is no longer maintain. I close this issue and we will now update the code if we have problem with some doxygen comments

**Comment by RetroAntho** [comment]
I saw this one to update
velocitys -> velocities
