### ISSUE TITLE
Link noclip

### ISSUE THREAD

**Issue by jeffythedragonslayer** [alekmaul/pvsneslib#143]
In the nogravityobject example, Link can noclip through the doorways in between two rooms:

<img width=300 src="https://user-images.githubusercontent.com/13253146/212257783-aef21414-c3d3-40b3-a9e1-8f126c96adec.png">

**Comment by alekmaul** [comment]
regarding 1st comment, you only need to change tile priority in tmx file, that's all.
update done in develop dranch

**Comment by alekmaul** [comment]
> Did you use Tiled to edit the priority? If so, how do I enable this left panel?
> 
> <img width=200 src="https://user-images.githubusercontent.com/13253146/215301078-01289920-e740-447f-8192-d50416a631c1.png">

WIki is your friend ;) https://github.com/alekmaul/pvsneslib/wiki/Update-Maps-in-Tiled
And please, use img instead of image , image displays too much big images ...

**Comment by alekmaul** [comment]
200 or 300 are sizes that make things more readable (well, if you agree :P)
