### ISSUE TITLE
missing human-readable SPC700 driver source

### ISSUE THREAD

**Issue by jeffythedragonslayer** [alekmaul/pvsneslib#145]
Assembly source for the SPC700 driver using the official SPC700 mnemonics is missing from https://github.com/alekmaul/pvsneslib/archive/refs/tags/4.0.1.zip.

The assembly source in sm_spc.asm is a bunch of `.byte` directives with hexadecimal SPC700 code.

**Comment by alekmaul** [comment]
No, you have it here : https://github.com/alekmaul/pvsneslib/tree/master/pvsneslib/snesmod
