### ISSUE TITLE
No$sns Setup debug frame name changed

### ISSUE THREAD

**Issue by jeffythedragonslayer** [alekmaul/pvsneslib#146]
I think the screenshot on https://github.com/alekmaul/pvsneslib/wiki/First-steps-with-No%24sns-emulator is out of date.  I don't see a "Debug Messages" frame, but there is "TTY Debug Message Limit."  It is not on/off either.

![image](https://user-images.githubusercontent.com/13253146/213908181-0136b1c0-73c7-413f-be91-101ceea9894c.png)

No$sns v1.5 looks like the wiki page.  I have pasted v1.6 screenshot above.

**Comment by RetroAntho** [comment]
Thank you, i updated the page : https://github.com/alekmaul/pvsneslib/wiki/First-steps-with-No$sns-emulator
