### ISSUE TITLE
gfx2snes tries to open BMP file when PNG specified on command line

### ISSUE THREAD

**Issue by jeffythedragonslayer** [alekmaul/pvsneslib#147]
```
$ gfx2snes -pc4 /E/SOM_Chocolate.png

gfx2snes: 'Opening graphics file: [E:/SOM_Chocolate.bmp]'
gfx2snes: error 'Can't open file [E:/SOM_Chocolate.bmp]'
```

**Comment by alekmaul** [comment]
you need to specify that it is a png file with -fpng flag, it is not an error without this flag.
Just take a look at options of gfx2snes

**Comment by alekmaul** [comment]
it is not hard, it is just that i do not want it to check the file to know exactly what is the content, even if the extension is not correct

**Comment by RetroAntho** [comment]
i find that the idea to detect format from file name was good (less parameters, less issues compared to the risk to have a file with an extension which is not the real format associated)
