### ISSUE TITLE
setScreenOff hangs for a long time in limbo

### ISSUE THREAD

**Issue by jeffythedragonslayer** [alekmaul/pvsneslib#149]
I tried inserting `setScreenOff();` into the sample projects hello_world and SimpleSprite - immediately after `ConsoleInit();` - and the screen stays black.  Mesen-SX reports that this is the disassembly:

```
setScreenOff:
	PHP
	LDA #$8F80
	BRK #$21
	BRK #$28
	RTL
```

The RTL jumps into a region of memory consisting entirely of 0's (BRK #$00) where it CPU stays for a long time.

**Comment by alekmaul** [comment]
I think it is fixed by your last PR
