### ISSUE TITLE
missing tcc configure script

### ISSUE THREAD

**Issue by jeffythedragonslayer** [alekmaul/pvsneslib#151]
The tcc configure script mentioned here:

https://github.com/alekmaul/pvsneslib/wiki/Compiling-from-sources

appears to be missing when you download the source code as a .zip or .tar.gz

On github, this complier folder appears to contain hyperlinks to the alekmaul/tcc and vhelin/wla-dx repos:

https://github.com/alekmaul/pvsneslib/tree/master/compiler

But when I clone alekmaul/pvsneslib, these hyperlinks turn into empty folders instead.

**Comment by alekmaul** [comment]
Sorry, but I don't understand what you really want about this issue ...

**Comment by RetroAntho** [comment]
I checked the content of 4.0.2 version. The compiler folder is also empty, i think it is related to github which does not "follow" submodules when providing sources

**Comment by alekmaul** [comment]
I think the new md file is not OK as we talked about git clone only.
