### ISSUE TITLE
submodules fail to be .gitignored

### ISSUE THREAD

**Issue by jeffythedragonslayer** [alekmaul/pvsneslib#154]
When I do a `git status` in `$PVSNESLIB_HOME`, I have (among several .d files) these unstaged changes:

```
        modified:   compiler/tcc-65816 (untracked content)
        modified:   compiler/wla-dx (modified content)
```

lines 21-23 of .gitignore are supposed to exclude these

**Comment by alekmaul** [comment]
hum, I don't know how to fix that

**Comment by alekmaul** [comment]
done ! thanks
