### ISSUE TITLE
CMake Error when building WLA under MINGW32

### ISSUE THREAD

**Issue by jeffythedragonslayer** [alekmaul/pvsneslib#156]
In MSYS2 MINGW 32-bit, after git cloning PVSnesLib with `--recurse-submodules`,

cd to pvsneslib/compiler dir, then `make wla`:

`
CMake Error: Could not create named generator MSYS Makefiles`

**Comment by RetroAntho** [comment]
I do not know if it will works on all configutations. (That is why we recommend to use same tools than us).
I will do the test, does someone else can do the same and give us feedback?

for the wla issue, i think it is more related to the tool itself or your distribution
