### ISSUE TITLE
Docs missing?

### ISSUE THREAD

**Issue by omgitsraven** [alekmaul/pvsneslib#16]
Why were the docs deleted? The commit says "(useless)", but where else are we supposed to see what the function arguments are?

**Comment by alekmaul** [comment]
Sorry, I updated read.md for the current link : 
http://www.portabledev.com/pvsneslib/doc/

**Comment by hoit** [comment]
Alekmaul,

You forgot this one on the main page :
https://github.com/alekmaul/pvsneslib

"You can find the library Doxygen documentation in the **'docs' directory**"

The link produce 404 not found.

**Comment by alekmaul** [comment]
I don't understand, it works for me :O ...
