### ISSUE TITLE
confusing "auto-detecting" error message from gfx2snes

### ISSUE THREAD

**Issue by jeffythedragonslayer** [alekmaul/pvsneslib#162]
The code in question:

```
//autodetect size if necessary
	if((size == 0) && (screen == 0))
	{
		if (quietmode == 0)
			printf("\ngfx2snes: %s 'Auto-detecting size of image blocks...'", RED_ERROR);

		clr = image.buffer[0]; //get the border color
		for(i=1; i<width; i++)
			if(image.buffer[i]!=clr)
				break;
```

This error is kind of confusing (it threw me for a loop when I was trying to convert an image.)  It sounds like the auto-detection of the image block size has failed, but gfx2snes hasn't really tried to auto-detect the size yet.  That happens immediately afterwards, in the for loops that increment i and then answer i-1 is stored.

I think the error should instead say that the size wasn't specified, so gfx2snes is falling back on auto-detection.

**Comment by alekmaul** [comment]
it is about size of image blocks, not size of image.
Which comment do you think could be better ?
