### ISSUE TITLE
WaitNVBlank label commented out

### ISSUE THREAD

**Issue by jeffythedragonslayer** [alekmaul/pvsneslib#168]
In interrupts.asm, the label for `WaitNVBlank` is commented out.  This caused this error in my project:

`title.obj: title.asm:147: FIX_REFERENCES: Reference to an unknown label "WaitNVBlank".`

When I uncommented it and rebuild the source, the project built successfully.

**Comment by alekmaul** [comment]
I can't remember why this one is commented, it's a bug, for sure
I will remove the comment

**Comment by alekmaul** [comment]
https://github.com/alekmaul/pvsneslib/commit/d7845ab746e8d3df4b63b4d1b46190ccef699ae6
