### ISSUE TITLE
HDMA channel 0 doesn't work, but all other HDMA channels do work

### ISSUE THREAD

**Issue by omgitsraven** [alekmaul/pvsneslib#17]
I'm trying to do some HDMA work with pvsneslib, but for some reason, my HDMAs are just ignored if I try to do them with channel zero.

This code has no visible result:
```
// ...

dmaMemory dmaPtr;
u8 hdmaTableScrolls[] = { /* ... */ };

REG_DMAP0 = 0b00000011;
REG_BBAD0 = 0x11;
dmaPtr.mem.p = (u8 *) hdmaTableScrolls;
REG_A1T0LH = dmaPtr.mem.c.addr;
REG_A1B0 = dmaPtr.mem.c.bank;

setScreenOn();

while(1) {
    REG_HDMAEN = 0b00000001;
    WaitForVBlank();
}
```

while this code works fine:
```
// ...

dmaMemory dmaPtr;
u8 hdmaTableScrolls[] = { /* ... */ };

REG_DMAP1 = 0b00000011;
REG_BBAD1 = 0x11;
dmaPtr.mem.p = (u8 *) hdmaTableScrolls;
REG_A1T1LH = dmaPtr.mem.c.addr;
REG_A1B1 = dmaPtr.mem.c.bank;

setScreenOn();

while(1) {
    REG_HDMAEN = 0b00000010;
    WaitForVBlank();
}
```
(and the same for all other channels.)

Does pvsneslib reserve the first HDMA channel for something on purpose, even though I'm not using any of its DMA functions in my code? (I should have enough channels just working with the remaining 7 for now, but it would have saved me a lot of debugging if I'd known this to begin with!)

**Comment by alekmaul** [comment]
Hi,
Yeah, i'm using 1st channel for all DMA transfert as you can see here : 
https://github.com/alekmaul/pvsneslib/blob/master/pvsneslib/source/dmas.asm
In my waitforvlank, I updated the OAM, so i'm using it.

**Comment by omgitsraven** [comment]
Is there a way to turn this off if we aren't using it?
If not, there should be a note in the docs that it isn't available...

**Comment by alekmaul** [comment]
To turn it off, just don't use functions which are updating OAM. But you're right, I will take this issue open and update the documentation.

**Comment by omgitsraven** [comment]
The project this was happening in didn't use OAM at all, I was purely using backgrounds.

**Comment by alekmaul** [comment]
Which function you used to put background on screen, certainly a DMA function :)

**Comment by alekmaul** [comment]
euh, you know, i'm just human, I can do some mistakes.
Again, i'm doing this lib on my free time, so please moderate what you say ....
If you are talking about DMA, just take a look at the lib, of when we are using a DMA channel for DMA stuffs ....
And yes, OAM are just about sprites functions (Object Attribute Memory).

**Comment by omgitsraven** [comment]
Sorry if I sounded rude, I was just confused. I thought the DMA was only required every frame to copy sprite tables or something. I assumed the DMA functions were synchronous, so they would be finished after the function call and no longer in use by the time my following DMA setup instructions were running.
