### ISSUE TITLE
Convert oamSetGfxOffset to ASM

### ISSUE THREAD

**Issue by malayli** [alekmaul/pvsneslib#178]
## Request
Convert `oamSetGfxOffset` to ASM because the current code is a C macro:
```
#define oamSetGfxOffset(id, gfxoffset) \
    oamMemory[id + 2] = (gfxoffset);   \
    oamMemory[id + 3] = (oamMemory[id + 3] & 0xFE) | ((gfxoffset >> 8) & 1);
```
https://github.com/alekmaul/pvsneslib/blob/master/pvsneslib/include/snes/sprite.h#L223

**Comment by alekmaul** [comment]
https://github.com/alekmaul/pvsneslib/commit/8a3c0ab492940106e42a6303b6b4459ed5af4ee5
