### ISSUE TITLE
constify gives "INPUT_NUMBER: Out of 8bit range"

### ISSUE THREAD

**Issue by omgitsraven** [alekmaul/pvsneslib#18]
I have an array in my code: `u8 hdmaTableGradient[138];`

If I make it `u8 hdmaTableGradient[137];`, everything works fine; it compiles, with at least 10% free in every bank.
If I make it `u8 hdmaTableGradient[138];`, everything looks fine until the Constify step, and then it says:
```
==============================
---constify v1.0.0 20140107---
------------------------------
(c) 2013 Alekmaul
Based on constify by Mic
==============================
Done! Moved 0 variables (0 bytes)
Doing obj files ...
wla-65816 -io template.asm template.obj
template.asm:16: INPUT_NUMBER: Out of 8bit range.
template.asm:16: ERROR: Couldn't parse "sta".
make.exe": *** [template.obj] Error 1
rm template.asm template.ps
```
and then the compilation stops.

What does this error mean? My program is relatively small, I wouldn't expect that I'm out of RAM already?

**Comment by alekmaul** [comment]
Hi, 
It is really strange ... I don't think constify is the problem, it is more wladx.
Could you please post the code to help me investogate the problem ?

**Comment by omgitsraven** [comment]
Out of curiosity, would it be possible to just skip this step until the bug is fixed? (Is it an optimization step that might not be needed, or is it something that it would be impossible to compile without?)

**Comment by alekmaul** [comment]
No, you can't . It is when the code is generated.  I will try to take a look this week end, but I'm really busy with real life this month. I will also try to clean the mode 7 code, with is useless in some parts.

**Comment by RetroAntho** [comment]
Hi,
I tried with the last version of wla 9.7b (available here : https://forums.nesdev.com/viewtopic.php?f=12&t=12334 ) but the error is still existing (i hoped it was a bug) :(

If you want to update wla version used by the lib, you will need to replace this line :
	$(AS) -io $< $@  
by this one 
	$(AS) -v -o $@ $<
in devkitsnes/snes_rules

**Comment by alekmaul** [comment]
The issue is more from TCC rather than wla. I have an updated version from mic_, I will check it solves the problem.

**Comment by Alirio926** [comment]
Hello!
I got this problem, it's alread adjusted???
some way to correct?

**Comment by alekmaul** [comment]
No it is not yet adjust, sorry

**Comment by alekmaul** [comment]
I checked the source code from @omgitsraven and I must say that It is not working like that on SNES.
SNES is not using compilers from the last generation, you must adapt your C source code to SNES.
You must initialize your variables outside your main function (the more you can use global variables, the best it is for pvsneslib) and use "const" variables as mush as possible if you're using some tables with constant values inside.
Also, it is not a constify issue but a wla-65816 when compiling asm file after constify. It is hanging on the asm file.
