### ISSUE TITLE
Different signature between bgInitTileSetLz and bgInitTileSet

### ISSUE THREAD

**Issue by RetroAntho** [alekmaul/pvsneslib#183]
Does this functions should work from the same way ? 

The signature of bgInitTileSetLz is different than bgInitTileSet.
The u16 tileSize parameter is missing in the bgInitTileSetLz.

Is it related to a technical reason or not ?

Thanks in advance

**Comment by alekmaul** [comment]
Nope, it is not related to technical reason.
bgInitTileSetLz  is using lzcompression, not the other one.
lzcompression is automaticaly knowing the size of compression, this is the reason why you do not have the size in this funciton.
