### ISSUE TITLE
Writes behave differently before and after setScreenOn?

### ISSUE THREAD

**Issue by omgitsraven** [alekmaul/pvsneslib#19]
I am having a bug that doesn't make any sense, so I can only imagine that pvsneslib must be doing something internally that is causing it... I have a block of code that works fine if it's placed outside the while(1) loop, but when placed inside, it seems to be writing to the wrong addresses.

Here is a project that I've stripped down to the basics that illustrate the problem: [hdmabug.zip](https://github.com/alekmaul/pvsneslib/files/2554941/hdmabug.zip)

The project uses an HDMA to write to CGRAM on different scanlines, to do a gradient effect. If the code setting up the hdma table in WRAM runs only once, then everything is fine. But if I try to change the table on every vblank, suddenly the HDMA clobbers all of CGRAM, as though something removed the terminating zero on the table (even though the code changing the colors doesn't touch it, as shown by it running identically in the initial setup!)

To see the results more clearly, please run the rom in BizHawk with the BSNES core, to have access to the Graphics Debugger window.

To demonstrate the bug:
1) `make` the rom, and run it in BizHawk. This looks exactly like it should.
2) Open template.c, and uncomment lines 96-99 (which are identical to lines 77-80), to try writing to the HDMA table each frame—although notice that this is writing THE SAME VALUES as above, so in theory it should be identical, right?
3) `make` the rom again, and run it in BizHawk—notice that the gradient still works, but all the other colors are all scrambled. Open the Graphics Debugger window and notice that CGRAM is filled with nonsense. It seems like the HDMA table is mostly still intact (the gradient still works!), but something must have happened to the terminating zero, and it just kept running, writing arbitrary data to the palette controller addresses instead? But what could have changed these values, if the exact same things were written in the exact same way as in the example that works, just in a later part of the program?

**Comment by omgitsraven** [comment]
Also, weirdly: the every-frame loop doesn't break anything if it only runs until `< 9` instead of `< gradientLength`?

**Comment by omgitsraven** [comment]
OK—I narrowed down the 'location' of where it breaks even further: it doesn't have anything to do with the while loop or `WaitForVBlank()`; removing the second loop and moving the first one to after `setScreenOn()` also causes it to break. But why would writes to WRAM hit the wrong address just because the screen is enabled?

**Comment by omgitsraven** [comment]
Or maybe it isn't even that simple? I now have a new example, that works as a workaround and lets me change the values every frame without corrupting CGRAM—but ONLY if I don't ALSO change it BEFORE the first frame? (And inexplicably, changing it before the first frame actually works fine too—it's really ONLY when it's changed in both places that it breaks.)

Here is this example, where I've moved `setScreenOn()` up to line 60, above all the HDMA setup business: [hdmabug2.zip](https://github.com/alekmaul/pvsneslib/files/2555174/hdmabug2.zip)
1) `make` with lines 78-81 commented out, and 97-100 uncommented. It works.
2) `make` with lines 78-81 uncommented, and 97-100 uncommented. It is broken.
3) `make` with lines 78-81 uncommented, and 97-100 commented out. It works again.

I thought it might have been a problem with accessing WRAM outside of vblank, but then why would it be fine in either place, just not in both? (I tried adding a check to not do anything in the while loop until one vblank has passed, but that just breaks it even in scenarios where it would have otherwise worked...???)

This makes no sense to me; hopefully I've provided enough information to narrow down what circumstances this does and doesn't occur in...

**Comment by omgitsraven** [comment]
so I'm starting to think that this is a consequence of writing to the WRAM that an HDMA is trying to read—I'm starting to suspect that my code to update the table wasn't fast enough to fit inside the vblank.

I'm attempting to be certain about this by using two tables and switching back and forth between them, but defining the second table causes https://github.com/alekmaul/pvsneslib/issues/18 to occur again, unfortunately >_>

(I had gotten around it until now by moving some unchanging arrays into externs, but I really do need everything to be writeable now...)

**Comment by omgitsraven** [comment]
ok wow yep—even without splitting it into two tables, I was able to get it to run fast enough just by taking out the multiplication arithmetic in my for loops (I saw people warn that it's slow on the SNES but holy heck I really had no idea HOW slow!!), and now my HDMA gradient looks fine. So the issue here is just, don't touch WRAM that a running HDMA is reading from, or everything gets messed up, seemingly.

**Comment by omgitsraven** [comment]
oof. I'm sorry, it didn't actually fix it, it just broke it in a way that was harder to notice. so I'm still not positive what's happening, until I can contrast it with a version that uses two tables, which I can't do until #18 is fixed

**Comment by RetroAntho** [comment]
Hi,
I tried hdmabug2 project with lines 78-81 uncommented and 97-100 uncommented but everything seems to work when i tried with no$sns.
If you have some perfomances issues, i think you could increase row by 5 (row=row+5) instead of increment 1 by 1 and access to row*5 + x
But after all replies, i am not sure to understand which issue is still existing.

**Comment by omgitsraven** [comment]
Ah, whoops, the difference is much smaller in no$sns for some reason, it's understandable to miss it. In bizhawk the colors were all very obviously scrambled. But the difference can still be seen by looking at the Palette table in no$sns:

With 78-81 commented (desired result)
![commented](https://user-images.githubusercontent.com/8540042/55282196-cec5d100-5315-11e9-821e-6d1f268a73da.png)

With 78-81 uncommented (buggy result)
![uncommented](https://user-images.githubusercontent.com/8540042/55282195-cbcae080-5315-11e9-88ad-3252fec6597a.png)

but anyway, I'll be honest, after this long I've forgotten most about this bug; I wound up finding some workaround at some point (I think by removing the multiplication and using two tables by accessing uninitialised memory, so I was never writing to the same table as the DMA was using...)

**Comment by alekmaul** [comment]
As we currently don't know what bug it is, I close it
