### ISSUE TITLE
Header name in hdr.asm is ignored

### ISSUE THREAD

**Issue by omgitsraven** [alekmaul/pvsneslib#20]
This one is visible right in the template project:

1) Look in hdr.asm; starting at line 15, there is:
```
.SNESHEADER
  ID "SNES"                     ; 1-4 letter string, just leave it as "SNES"

  NAME "LIBSNES TEMPLATE     "  ; Program Title - can't be over 21 bytes,
  ;    "123456789012345678901"  ; use spaces for unused bytes of the name.
```
2) run `make`; it will end with:
```
===============================
---snestools v0.3.0 20140726---
-------------------------------
(c) 2014 Alekmaul
===============================

File [template.sfc] has no header.

Change title to [TEMPLATE             ] ...
Change Checksum to 2602h and Checksum complement D9FDh..
Done!
```
3) Run the rom in an emulator that displays the header name (i.e. SNES9x); it will say "TEMPLATE", not "LIBSNES TEMPLATE".

This bug is pretty minor of course :) but I thought I'd mention it!

**Comment by alekmaul** [comment]
The reason is this line in makefile
`$(SNTOOLS) -hi! $(GTITLE) $(TARGET).sfc`
So, it put $(GTITILE) instead of what is in hdr.asm.

GTITLE is declared also in makefile
`GTITLE 		:= -ht"$(TARGET)"`

You just have to remove it in the SNTOOLS line and the label in hdr.asm will stay.

**Comment by omgitsraven** [comment]
changing `$(SNTOOLS) -hi! $(GTITLE) $(TARGET).sfc` to `$(SNTOOLS) -hi! $(TARGET).sfc` just forces the name to be "LIBSNES DEFAULT CART", it still doesn't show what's in hdr.asm

changing `GTITLE 		:= -ht"$(TARGET)"` to `GTITLE 		:= -ht"MY ROM NAME"` worked though, thanks!
