### ISSUE TITLE
Make it possible to overwrite the "src" folder with the name of your choice

### ISSUE THREAD

**Issue by AndyDragon1998** [alekmaul/pvsneslib#203]
Currently the .c and .h files are by default expected in a file named src. Which most likely is  a throwback to how Visual Studio or CodeBlocks handles most of the program text.

This is however a small eyesore to projects made with notepad and terminal. 

I propose a system where by default the src remains as it is, however users have the ability to overwrite this folders  name in the makefile if they want to do so.

Thank you!
Sincerely,  Drakonchik!

**Comment by RetroAntho** [comment]
The case has been manage by @kobenairb in this commit on develop branch : https://github.com/alekmaul/pvsneslib/commit/d794667219b6fee984fd3bd0e2661f7ad48d2104

It should works if you set the SRC variable before the include of snes_rules :
`include ${PVSNESLIB_HOME}/devkitsnes/snes_rules)`

**Comment by kobenairb** [comment]
Sorry for the late, this issue should be fixed par the following PR https://github.com/alekmaul/pvsneslib/pull/245

**Comment by alekmaul** [comment]
Fixed
