### ISSUE TITLE
pad state sometimes reset

### ISSUE THREAD

**Issue by hoit** [alekmaul/pvsneslib#21]
Hello,

I tried to detect while button is pressed but sometimes, its state seems to be reset.

You can test it with this minimal code, you will see that "released" appear (very quickly) to the screen even if you keep button pressed.

```
#include <snes.h>

extern char snesfont, snesfont_end;
bool isPressed = false;

int main(void)
{
	consoleInit();
	consoleInitText(0, 0, &snesfont);
	
	unsigned short pad0;
	
	setMode(BG_MODE1,0);
	bgSetDisable(1);
	bgSetDisable(2);
	setScreenOn();
	
	while(true)
	{
		pad0 = padsCurrent(0);
		if (pad0 & KEY_DOWN) 
		{
			if(!isPressed)
				isPressed = true;
		}
		else
			isPressed = false;
		
		if(isPressed)
			consoleDrawText(0,8, "PRESSED ");
		else
			consoleDrawText(0,8, "RELEASED");
		
		WaitForVBlank();
	}
	return 0;
}

```

Is it a bug ?

Thanks for your help !

**Comment by alekmaul** [comment]
OK, that's odd. Will check that. Perhaps a compiler issue :/.

**Comment by hoit** [comment]
I opened a topic on nesdev forum and they gave the solution :)

http://forums.nesdev.com/viewtopic.php?f=12&t=18635&sid=4b310a2d123203397aad4f02895e111d

But for now, it is not clear for me to implement it.

**Comment by alekmaul** [comment]
yeah, strange. It seems that we need to check for value and then when register is cleared; I don't think it is the solutio ...,

**Comment by hoit** [comment]
I forgot to reply here. I confirm that that it was not the solution. If anybody has clues...

**Comment by hoit** [comment]
tested with the latest pvsneslib version, the bug does not exists anymore :) I close it, thanks a lot !
