### ISSUE TITLE
Add a note to oamSetVisible()

### ISSUE THREAD

**Issue by malayli** [alekmaul/pvsneslib#215]
# Request

The current signature of `oamSetVisible()` contains this comment in `sprite.h` but it does not mention that the sprite is set out of bounds:
```
/*! \brief Hide or show a sprite
    \param id the oam number to be set [0 - 127] * 4 because of oam structure
    \param hide	0 or 1 to hide / see oam
*/
void oamSetVisible(u16 id, u8 hide);
```
https://github.com/alekmaul/pvsneslib/blob/develop/pvsneslib/include/snes/sprite.h#L236-L240

## Add a note
I suggest to add this note:
```
When OBJ_HIDE is passed, the sprite is set at these coordinates: x = 255, y 240.
Therefore when a sprite is hidden and it is needed to show it again (use OBJ_SHOW), it is necessary to reset the sprite coordinates with oamSetXY().
```

## Add a tip
I also suggest to add this tip to the comment:
```
If the sprite needs to be hidden and keep its coordinates, please use oamSetGfxOffset instead by passing a transparent tile.
```

## Optional
`oamSetVisible` could be renamed to `setOutOfBounds` as it is closer to the expected behavior.
As this change breaks the public API, this renaming should be part of a major version of PVSnesLib.

**Comment by alekmaul** [comment]
I do not agree with your last comment. I think that the behavior of visible / not visible is the good one with this function.
But i agree that it is not clear, I will add your 1st comment.

**Comment by malayli** [comment]
@alekmaul Ok fine for me, that's why I marked as optional.
You can close this issue when it's done.
Thank you!
