### ISSUE TITLE
So, I was trying to draw a sprite on a  Mode 3 bg, and instead of 16x16 it draws a 16x8 one

### ISSUE THREAD

**Issue by Gabryx64** [alekmaul/pvsneslib#219]
So, I was trying to draw a sprite on a  Mode 3 bg, and instead of 16x16 it draws a 16x8 one.

**Comment by Gabryx64** [comment]
After some testing, changing the mode and sizes from the code and also changing the -gs parameter for GFXCONV didn't do anything, I still got these tiles: 16x8 tile that is the first half of the sprite (the top half), then the top-right quarter, then the bottom-left quarter, the lower half, and the bottom-right quarter. and after a weird amount of spaces that i cannot count, it shows the top-left quarter.

**Comment by Gabryx64** [comment]
After some other fiddling, if i make the spritesheet have 1 8x8 tile per 16x8 space it shows it in the previously said order just that this time the last sprite after some spaces is the first one

**Comment by alekmaul** [comment]
you can't do 16x8 sprites with gfx2snes, only 8x8 or 16x16 or 32x32, so square sprites.

**Comment by Gabryx64** [comment]
> you can't do 16x8 sprites with gfx2snes, only 8x8 or 16x16 or 32x32, so square sprites.

No, the problem is that its drawing 16x16 tiles sometimes as 16x8 abd sometimes as 8x8, which is not what i want to do.

**Comment by alekmaul** [comment]
ok, hum... It will be difficult to help you without your source code... If it possible to share it here? (even if mode3 is nto the mode we use often on SNES, especially because it uses lots of VRAM)

**Comment by Gabryx64** [comment]
> ok, hum... It will be difficult to help you without your source code... If it possible to share it here?

Yeah, I'll post it here on gh since I was already going to do that

**Comment by Gabryx64** [comment]
https://github.com/Gabryx64/wwl

**Comment by alekmaul** [comment]
your png sprite file is not correct, it must be 16pix width and what you want for height (16pix minimum for one sprite). I think it's better to continue on discord if you're OK. You have a specific #support channel for that ;).
If you're ok, we are going to close this issue.

**Comment by Gabryx64** [comment]
Ok
