### ISSUE TITLE
setMosaicEffect - MOSAIC_OUT issue ?

### ISSUE THREAD

**Issue by hoit** [alekmaul/pvsneslib#22]
Hi,

I think MOSAIC_OUT parameter doesn't work in setMosaicEffect function. I tried sample (in graphics\Effects\MosaicShading) and the last call to setMosaic function don't have effect, the screen still stay with big pixels.

I have a remark about general debug in pvsneslib : i don't know if it would be possible without impact performances, but it should be good to define a "debug mode" (if you have #define PVSNESLIB_DEBUG in your code !) that avoid you to do some errors (like you can do it with assertions).

**Comment by alekmaul** [comment]
Regarding mosaic effect, I will check (when Real Life will leave me some time ...)
About debugging, you can use no$sns (windows only) I did a function to send it a message

**Comment by alekmaul** [comment]
I just fixed mosaic in/out effect and push fix on master
