### ISSUE TITLE
sprintf issue with 32 bits variables

### ISSUE THREAD

**Issue by alekmaul** [alekmaul/pvsneslib#220]
When you want to use u32 and put content in a string, the result is not OK
here is an example:
`sprintf((char *)tmphud, "%05Lu", (u32) hiscore);`
example, if hiscore is 0000c350 for 50000, result is garbage

tmphud is defined with `u8 tmphud[16];
`

**Comment by darkain** [comment]
So, it turns out the results are not entirely garbage, instead, it is only reading 16-bits at a time. So if you pass in a 32-bit value, you can print it as two consecutive 16-bit values. This, of course, isn't ideal.

**Comment by alekmaul** [comment]
Well, I need to investigate again this issues. I thought it was fixed with last version of tcc.

**Comment by alekmaul** [comment]
I tested on Hello world example
![image](https://github.com/alekmaul/pvsneslib/assets/2528347/d63572a4-0d6b-44fd-ad5d-6ae283fea1f3)
with:

```
u32 hiscore;
u8 tmphud[16]; 

    hiscore=0xdeadcafe;
    sprintf((char *)tmphud, "%05Lu", (u32) hiscore);
    consoleDrawText(10, 20, tmphud);
```

And it works, I close this defect.
