### ISSUE TITLE
Re-definition of VRAM_ADRSTINC_128

### ISSUE THREAD

**Issue by daniel-starke** [alekmaul/pvsneslib#221]
From a programmers perspective it makes no difference which value is used if both values do the same and it is only to control the behavior. Which is the case for `VRAM_ADRSTINC_128`. Therefore, I suggest to remove one of the definitions of `VRAM_ADRSTINC_128` or comment one out to avoid re-definition of the same enumeration value.

See:
https://github.com/alekmaul/pvsneslib/blob/862adbf4831cd6033f01433d01f0da4e405d864f/pvsneslib/include/snes/video.h#L49-L50

**Comment by kobenairb** [comment]
Hi @daniel-starke,

 I'm agree with you. I added a test in tcc to report an error when redefining enumerator (see https://github.com/kobenairb/tcc/commit/323d2c77496f21647b0305720ae1a7670cf98e1f).
 @alekmaul, do you think it's oaky to comment or remove one of the definitions ?
I will create my PR for tcc once this ticket is fixed.

**Comment by alekmaul** [comment]
yeah, I really don't know why i did that :(
I will fix it with only one define
