### ISSUE TITLE
constify broken

### ISSUE THREAD

**Issue by daniel-starke** [alekmaul/pvsneslib#222]
For my understanding constify is supposed to move static const variables out of the RAM section to the rodata section to avoid duplication in RAM. However, that does not seem to work correctly.
I have several static const arrays [in my project](https://github.com/daniel-starke/BombNBreakSNES), e.g. `playerTileMap` in `main.c` but I only get  `constify: Done 'Moved 0 variables (0 bytes)'`.
Therefore, I suspect that the program is broken. Or does it require some special syntax in C to work correctly?

**Comment by alekmaul** [comment]
The declaration is:
**const <typeof variable> <variablename>=
{
};**

You can't put your variables in an include file, it will not analyze it :(. The variables must be in a C file compiled with tcc.

**Comment by daniel-starke** [comment]
Thank you for the quick response.
It seems that the issue was, that the `{` was on the same line as the `=`. Moving it to the next line seems to fix the issue.
Would be nice it was also recognizing `{` on the same line. I.e.:
```C
static const type_of_variable variablename[] = {
};
```

**Comment by alekmaul** [comment]
Yeah, that's right.  We will certainly do that when constify will be embeded inside tcc ;)

**Comment by daniel-starke** [comment]
You mean the official tcc repository or the fork here?

**Comment by alekmaul** [comment]
a fork here, official tcc is no more maintained
