### ISSUE TITLE
OBJ_LARGE Sprite size

### ISSUE THREAD

**Issue by hoit** [alekmaul/pvsneslib#23]
Hello,

I would like to load sprite with 8x8 size but 64x64 for OBJ_LARGE.
I took sample in Sprite.h and i created #define OBJ_SIZE8_L64	(1<<6) but it not so easy :)

If you do not think to add this, can you explain me what should change to works ?

Is there a way to rotate picture without using MODE 7 ?

Thanks

**Comment by alekmaul** [comment]
To create a 64X64 sprite, you need to use 16x16 (64x64 for LARGE) or 32x32 (64x64). You can't have 8x_ and 64x64 for large (see REG_OBSEL in sprite.h).
And no, you can't rotate a screen without using mode 7.

**Comment by alekmaul** [comment]
you're right, i replied too fast ... strange.
I will check. I must say that I never use 64x64 sprites , only 16x16 and 32x32.

**Comment by hoit** [comment]
Hi,
In fact it works. I think i was tired when i tried it.

With this 3 new define in Sprite.h, you can get all existing size :

#define OBJ_SIZE8_L32	(1<<5) /*!< \brief default OAM size 8x8 (SM) and 32x32 (LG) pix for OBJSEL register */
#define OBJ_SIZE8_L64	(1<<6) /*!< \brief default OAM size 8x8 (SM) and 64x64 (LG) pix for OBJSEL register */
#define OBJ_SIZE16_L64	(1<<7) /*!< \brief default OAM size 16x16 (SM) and 64x64 (LG) pix for OBJSEL register */

I advise to harmonize existing names to get this :

#define OBJ_SIZE8_L16	(0<<5)	/*!< \brief default OAM size 8x8 (SM) and 16x16 (LG) pix for OBJSEL register */
#define OBJ_SIZE8_L32	(1<<5) /*!< \brief default OAM size 8x8 (SM) and 32x32 (LG) pix for OBJSEL register */
#define OBJ_SIZE8_L64	(1<<6) /*!< \brief default OAM size 8x8 (SM) and 64x64 (LG) pix for OBJSEL register */
#define OBJ_SIZE16_L32	(3<<5)	/*!< \brief default OAM size 16x16 (SM) and 32x32 (LG) pix for OBJSEL register */
#define OBJ_SIZE16_L64	(1<<7) /*!< \brief default OAM size 16x16 (SM) and 64x64 (LG) pix for OBJSEL register */
#define OBJ_SIZE32_L64	(5<<5)	/*!< \brief default OAM size 32x32 (SM) and 64x64 (LG) pix for OBJSEL register */

But it is more heavy because you need to adapt all samples...

**Comment by RetroAntho** [comment]
if you are agree with that, let me know and i will try to do it (i never used git).
I created a real account for that :)

**Comment by alekmaul** [comment]
ok, so do it. 1st, clone the repo, create a branch, do the changes, and after, just do a change request and I will agree it :)
Nice to see that I have some so nice followers on PVSNeslib :)

**Comment by hoit** [comment]
i close the issue, it is now implemented in pvsneslib :)
