### ISSUE TITLE
[Feature] setFadeEffectEx

### ISSUE THREAD

**Issue by malayli** [alekmaul/pvsneslib#230]
# Feature request
Creating this function will allow a control on the duration of fade in or fade out:
```
/*! \fn  setFadeEffectEx(u8 mode, u8 framesNumber)
    \brief Do a fadein or fadeout effect.
    \param mode	(FADE_IN  = black to complete light, FADE_OUT = light to black)
    \param framesNumber the number of frames
*/
void setFadeEffectEx(u8 mode, u8 framesNumber);
```

Is it possible to create this function?

## Notes
I'm note sure if it's relevant to set the framesNumber type to `u16`.
I think that `u8`type should be enough for `framesNumber`.

**Comment by alekmaul** [comment]
fixed by commit [@ #](https://github.com/alekmaul/pvsneslib/commit/68e92ca6ab91bf867bd84cd8e690db6f9e40a37a)
