### ISSUE TITLE
MODE7 sample

### ISSUE THREAD

**Issue by hoit** [alekmaul/pvsneslib#24]
Hello,

I tried Mode7 sample under graphics/Backgrounds folder but it miss few lines of code.
sz et sx variable are declared but not used (except to increase/decrease it).

scanPads() function is called and i thought it was no more useful (already included in other function?) but in this sample if i remove it, keys are not updated. Maybe because Mode7 functions are specific ? (like consoleVblankMode7)

I tried setMode7Angle function but it don't seems change something.
I see in source code that 2 other functions exists (these functions are not available in documentation) : setMode7MoveForwardBack and setMode7MoveLeftRight but they give "implicit declaration of function ...." when i use it.

Could you please update this sample ?

Thanks

**Comment by alekmaul** [comment]
Hi,
Thanks for your reply. But I think I will remove mode7 because it is not really useful regarding the functions I currently did about it (only BG rotation, nothing related to "mario kart" like implementation.

**Comment by hoit** [comment]
I find it is not a good idea. If you remove it, nobody will try to improve it or implement new functionalities for this mode. I think you already spent a lot of time on it so it should be better to separate in a new branch or in develop branch and why not create a roadmap to specify list of improvements to do :)

**Comment by alekmaul** [comment]
ok, right. I will update the example and try to clean a little mode7 code (some const are not used by the code) :)

**Comment by RetroAntho** [comment]
I saw this link on mode 7 implementation :
Super-Nintendo Mode 7 : https://github.com/Kannagi/SNES-Mode7
Video: https://youtu.be/ik8gEbf3Et4?t=32

I think it will be useful :)

**Comment by mills32** [comment]
Hi alekmaul, you did a great work with this code!.

I also wanted to test some "mario kart" mode 7, and I saw this video about how it works:
https://youtu.be/K7gWmdgXPgk?t=857

I remember some time ago I compiled the mode7 sample, and it has all necesary functions to do it (I think). You just have to enable a mode 7 background, and then change the scalling every scanline using HDMA. Now scrolling and rotating the background, with the pvsneslib functions you already have, will result in a fake camera moving above the plane.

My programming skills are not good, so I was not able to test it.

Also you can add a sample using HDMA to change the scroll every scanline to make wavy backgrounds.

Thanks!

**Comment by alekmaul** [comment]
Nice video, thanks.
Sadly, as said just previously in this post, I currently have not yet implement it. You can try to check kannagy source code (https://github.com/Kannagi/SNES-Mode7)

**Comment by mills32** [comment]
I did not understand very well the assembly source code from kannagy, so I used the HDMA sample from pvsneslib, and figured out how to change other registers (not just the brightness).

I "kind of" made it work, using only c code and pvsneslib. But the math involved in rotation and zoom in mode 7 is not easy, and the perspective is wrong. 

I hope this image can be seen, (for some time at least):
http://i64.tinypic.com/28ujmgz.jpg

If someone is interested and knows a bit of math... :)

**Comment by hoit** [comment]
You can upload a picture and display it directly in github without using a link on internet. You just need to drag and drop it in the text area.

You first result is cool and near the final known result.
Is it possible to upload it here (you can do it with zip files like with pictures) ?

**Comment by mills32** [comment]
Ok here it is.

![Untitled](https://user-images.githubusercontent.com/25790927/58246212-c0fd5c80-7d56-11e9-8e93-1f4b800af210.png)

I'm going to try a few things just in case I can make the perspective look ok. If I can't fix it, I'll upload the code.

**Comment by mills32** [comment]
I got it!. It does not rotate, (That part is not easy...), but it looks perfect.

I used the sky and map from kannagy's sample:
 
![screenshot](https://user-images.githubusercontent.com/25790927/58256619-9ec40880-7d6f-11e9-9281-a1ab231fddca.png)

Here you have the source and compiled sample:

[Mode7_Perspective.zip](https://github.com/alekmaul/pvsneslib/files/3212364/Mode7_Perspective.zip)

**Comment by hoit** [comment]
I tried it ! thanks, it is really impressive. There no much line to produce it :)
The format of different tables doesn't seems me really clear but i guess that it is DMA constraint ?
I am sure that Alekmaul will be happy too to use it and improve the lib!

What's your next objective ? :)

**Comment by mills32** [comment]
> I tried it ! thanks, it is really impressive. There no much line to produce it :)
> The format of different tables doesn't seems me really clear but i guess that it is DMA constraint ?
> I am sure that Alekmaul will be happy too to use it and improve the lib!
> 
> What's your next objective ? :)

You have to watch this video to understand how the tables work: https://www.youtube.com/watch?v=K7gWmdgXPgk&t=526s

**Comment by alekmaul** [comment]
@mills32 , can I add your example to snes examples for next release ?
I will modify it a bit, and don't worry, I will credit you about source code ;)

**Comment by mills32** [comment]
Of course you can.

Thanks!

**Comment by hoit** [comment]
Hi,

Thank you, the mode 7 code has been cleaned by Alekmaul for the last release and he added the new perspective sample.

The next step will be probably to add functionality to turn, if someone want to help :)

I close the issue
