### ISSUE TITLE
snes_vblank_count size mismatch

### ISSUE THREAD

**Issue by darkain** [alekmaul/pvsneslib#242]
snes_vblank_count is defined as 8-bit in the ASM, but 16-bit in the C code. This will lead to corrupting the neighboring byte.

https://github.com/alekmaul/pvsneslib/blob/develop/pvsneslib/source/consoles.asm#L43
```
snes_vblank_count       DB
```

https://github.com/alekmaul/pvsneslib/blob/develop/pvsneslib/include/snes/console.h#L48
```
extern u16 snes_vblank_count;
```

**Comment by alekmaul** [comment]
How can I was blind about this one o_O :O !!!!
thanks a lot, i will fix it

**Comment by darkain** [comment]
Fixed with: https://github.com/alekmaul/pvsneslib/commit/8f32a68f0301ce82ec79c5b8c25fada21dcece97
