### ISSUE TITLE
[Dummy issue] Use it to store pictures for Wiki pages

### ISSUE THREAD

**Issue by RetroAntho** [alekmaul/pvsneslib#26]
**In wiki pages, when you want to display an image, you have to give its link. To avoid to lost pictures in a future if it is store anywhere on internet, i advise to use this page.**

For no$sns page :

![image](https://user-images.githubusercontent.com/48180545/56092236-b202cf00-5eb9-11e9-93af-5773d029de38.png)

![image](https://user-images.githubusercontent.com/48180545/56092240-bc24cd80-5eb9-11e9-9b31-8ef8675ea79f.png)

**Comment by RetroAntho** [comment]
Community FAQ : Common errors => Colors of my loaded picture are false

![PaletteIssueAfterUsingPaint](https://user-images.githubusercontent.com/48180545/56434580-727f1d00-62d5-11e9-94a1-1feb1e9d591b.png)
![PaletteIssueBasePicture](https://user-images.githubusercontent.com/48180545/56434581-727f1d00-62d5-11e9-8762-095da6a992b6.png)
![PaletteIssueMoveTransparencyColor](https://user-images.githubusercontent.com/48180545/56434582-7317b380-62d5-11e9-80cb-c934547af546.png)
![PaletteIssueRemoveUnusedColors](https://user-images.githubusercontent.com/48180545/56434583-7317b380-62d5-11e9-9670-497e43cb22b2.png)

**Comment by hoit** [comment]
"The Last Super" game source code (from Dr. Ludos) updated to work with PVSneslib v3 : 

[TheLastSuper_sourcecode.zip](https://github.com/alekmaul/pvsneslib/files/6556286/TheLastSuper_sourcecode.zip)

The file is used in this wiki page :
The https://github.com/alekmaul/pvsneslib/wiki/Community-code

**Comment by hoit** [comment]
on the "installation with windows" page : https://github.com/alekmaul/pvsneslib/wiki/Installation-with-Windows
in gcc section, the error message you may have:
![smConvError](https://user-images.githubusercontent.com/981773/120016823-5e926300-bfe5-11eb-9ec3-c76223072ae0.png)

**Comment by RetroAntho** [comment]
home page logo :

![pvsneslibLogo](https://user-images.githubusercontent.com/48180545/170839910-0455245c-6af4-495a-8165-24d28592dd85.jpeg)


installation page 

![pvsneslibHomeVariableWindows](https://user-images.githubusercontent.com/48180545/170839914-f5f21198-2df9-4190-ae72-ee459c4bc790.png)
:

**Comment by RetroAntho** [comment]
community code page - Update the priority of a tile map area
![updateTileMapAreaWithPriority-preview](https://user-images.githubusercontent.com/48180545/187201833-17357bb2-eed4-48b8-a3b1-64a6538ece08.png)

**Comment by alekmaul** [comment]
wiki map engine
![map_ex0](https://user-images.githubusercontent.com/2528347/189572543-d96c0012-fe31-4573-805c-b8ac241b25c7.png)
![map_ex01](https://user-images.githubusercontent.com/2528347/189572545-3e1f3520-6ce6-4ec2-8aeb-08a67351e5c2.png)
![map_ex02](https://user-images.githubusercontent.com/2528347/189572546-41ecc736-18b3-43e3-a77d-56f5839715ac.png)
![map_ex03](https://user-images.githubusercontent.com/2528347/189572548-5e6aee1f-9d3c-4a36-9127-dc0a746aedb3.png)
![map_ex04](https://user-images.githubusercontent.com/2528347/189572549-38d7b500-bd8f-4f85-9752-b3abb2a6296f.png)
![map_ex05](https://user-images.githubusercontent.com/2528347/189572551-e044d8ed-fcdd-4fec-b767-b332ec6ec2c8.png)
![map_ex06](https://user-images.githubusercontent.com/2528347/189572553-3726bd76-47a7-4679-aeae-d83630270746.png)
![map_ex06_1](https://user-images.githubusercontent.com/2528347/189572554-ccd10fbe-f99b-4c0f-9605-2cb97ec9aa50.png)
![map_ex06_2](https://user-images.githubusercontent.com/2528347/189572555-3d1d7c82-471d-445e-895f-9c0484492cba.png)
![map_ex06_3](https://user-images.githubusercontent.com/2528347/189572557-3e4c4d01-8944-495f-9536-b5a46ce5a1ff.png)
![map_ex07](https://user-images.githubusercontent.com/2528347/189572558-ee653ca6-8320-40f9-a92f-1bee1f666ea6.png)
![map_ex08](https://user-images.githubusercontent.com/2528347/189572560-0160fad9-f301-4c15-a92c-c1556189a772.png)
![map_ex08_1](https://user-images.githubusercontent.com/2528347/189572561-247168ab-a883-4262-ae35-90fda249dbdd.png)
![map_ex08_2](https://user-images.githubusercontent.com/2528347/189572562-83e1c77e-d65e-4901-ac0f-18c22b728af6.png)
![map_ex08_3](https://user-images.githubusercontent.com/2528347/189572563-5e68127c-8283-4298-8001-5cdd2bf552f8.png)

**Comment by alekmaul** [comment]
![pvsneslib_logo](https://user-images.githubusercontent.com/2528347/198873675-57a9670a-3ef2-4fc9-a5b0-e2e9fcf62cc6.png)
![comm_keen_map1](https://user-images.githubusercontent.com/2528347/198873690-096676c1-71af-4082-93ca-a2cf0a7a04c1.png)
![map_tut00](https://user-images.githubusercontent.com/2528347/198873692-5e1ee6d1-5ca0-4c11-a40c-196acb4853b4.png)
![map_tut01](https://user-images.githubusercontent.com/2528347/198873694-4672ac17-2b43-4978-8770-ad2c188ac272.png)

**Comment by RetroAntho** [comment]
![openMPTSetup](https://github.com/alekmaul/pvsneslib/assets/48180545/ce2998d8-3687-4837-8fd6-dcce030a1e35)
![openMPTCompression](https://github.com/alekmaul/pvsneslib/assets/48180545/cf38c2cb-eb29-4ba4-a764-ea7fe5338963)
Used in the FAQ

**Comment by alekmaul** [comment]
![fasthi_1](https://github.com/alekmaul/pvsneslib/assets/2528347/c2ace721-19dc-4a1f-a958-0f17c58ef7d2)
![fasthi_2](https://github.com/alekmaul/pvsneslib/assets/2528347/779a6226-4ef1-4577-9bf1-1b3c9b91d976)

**Comment by alekmaul** [comment]
![Image](https://github.com/user-attachments/assets/6e5ec9f1-236f-440c-bd02-86b040f19283)
