### ISSUE TITLE
BG3_MODE1_PRORITY_HIGH not working with map engine

### ISSUE THREAD

**Issue by DigiDwrf** [alekmaul/pvsneslib#261]
Hi, I'm trying to create a BG3 HUD for an rpg/adventure like game (e.g. zelda), but I'm not able to render BG3 layer on top (it renders on the back), I don't know if there's any fuction to set priority for BG3 layer manually either.

**Comment by alekmaul** [comment]
You have an example here who help you with this feature.
https://github.com/alekmaul/pvsneslib/tree/master/snes-examples/graphics/Backgrounds/Mode1BG3HighPriority

**Comment by DigiDwrf** [comment]
of course! but is not working, I've followed all the steps, this is part of my code, you can see it's set up:
 
    ...

    // Fade out
    setFadeEffectEx(FADE_OUT, 3);
    WaitForVBlank();

    // Init layer with tiles and init also map length 0x6800 is mandatory for map engine
    bgSetMapPtr(0, 0x6800, SC_64x32);
    bgSetMapPtr(2, 0x7400, SC_32x32);
    bgInitTileSet(0, &overworld_tileset, &overworld_palette, 1, (&overworld_tileset_end - &overworld_tileset), 16 * 2, BG_16COLORS, 0x2000);
    bgInitTileSet(2, &hud_tileset, &hud_palette, 0, (&hud_tileset_end - &hud_tileset), 4 * 2, BG_16COLORS, 0x4000);

    // load HUD
    bgInitMapSet(2, &hud_display, (&hud_display_end - &hud_display), SC_32x32, 0x7400);

    // Now Put in 16 color mode and disable Bgs except current
    setMode(BG_MODE1, BG3_MODE1_PRIORITY_HIGH);
    bgSetDisable(1);
    // Init Sprites palette

    setPalette(&keno_palette, 16 * 8, 16 * 2);

    // Init sprite engine (0x0000 for large, 0x1000 for small)
    oamInitDynamicSprite(0x0000, 0x1000, 0, 0, OBJ_SIZE8_L32);

    // Object engine activate
    objInitEngine();

    // Init function for state machine
    objInitFunctions(0, &keno_init, &keno_update, NULL);

    // Load all objects into memory
    objLoadObjects((char *)&overworld_objects);

    // Load map in memory and update it regarding current location of the sprite
    mapLoad((u8 *)&overworld_bg1, (u8 *)&overworld_definitions, (u8 *)&overworld_attributes);`

    // playing loop
    while (1)
    {
          // Update the map regarding the camera
          mapUpdateCamera(*keno_ox + 8, *keno_oy + 8);
          mapUpdate();
      
          // Update all the available objects
          objUpdateAll();
      
          // prepare next frame and wait vblank
          oamInitDynamicSpriteEndFrame();
          WaitForVBlank();
          mapVblank();
          oamVramQueueUpdate();
   }
    ...

**Comment by DigiDwrf** [comment]
I tried ` dmaCopyVram();` too but it's the same result

**Comment by DigiDwrf** [comment]
btw, I noticed that the definition is "BG3_MODE1_PRORITY_HIGH" but it could be "BG3_MODE1_PRIORITY_HIGH", it's not an big issue though, just a spelling mistake, but can lead to confusion.

**Comment by alekmaul** [comment]
hum, the example seems working as you can see if you run the bin file of it
![image](https://github.com/alekmaul/pvsneslib/assets/2528347/48684e7d-b5f7-4418-bdf1-8f0a1c1ace2e)

You're using bgInitMapSet for your BG3, perhaps the issue is here
I fixed the typo, thanks for that!
