### ISSUE TITLE
New to PvSNESlib; HDMA

### ISSUE THREAD

**Issue by EdyGH36** [alekmaul/pvsneslib#27]
Hey there. I'm new to PvSNESlib and I understand that you successfully used HDMA for torch effect in your Sidney game. How did you made it to emit this effect? I really want to play around with HDMA for 2.5D Perspective, Lights, Transitions and so on. Please can I get an example for HDMA, not the only  Brightness gradient command? 
Thank you for understanding and I apologize for posting this request on your Youtube Channel.

**Comment by hoit** [comment]
Hi and welcome to pvsneslib community :) i can’t help you for that but if you find some informations that could be interesting for everybody, do not hesitate to create/update wiki pages or new sample. We will be happy to get more informations on hdma (or other).

**Comment by alekmaul** [comment]
What do you want exactly regarding HDMA ? If it is about torch effect, it is more a sub/add effect than an HDMA effect.

**Comment by EdyGH36** [comment]
HDMA for 2.5D Parallax Scrolling like in Sonic and Donkey Kong Country 2.

**Comment by hoit** [comment]
I do not represent myself exactly what you need but i think the last commit did by Alekmaul (which integrate the parallax scrolling) should respond to your needs. Can you confirm it ?

Here is the link to the sample : https://github.com/alekmaul/pvsneslib/tree/master/snes-examples/graphics/Effects/ParallaxScrolling
