### ISSUE TITLE
Makefile claims that the snes_rules file doesn't exist.

### ISSUE THREAD

**Issue by Flamethwarrior257** [alekmaul/pvsneslib#270]
<img width="959" alt="nosuchfileordirectory" src="https://github.com/alekmaul/pvsneslib/assets/162084184/b24acb16-61bb-4111-9dd3-cfe36170a20c">
For some reason, even though the directory and file exists, Makefile claims that "No such directory or file exists" and that there's "no rule to make target". I don't know if it has anything to do with the "snes_rules" file (Which is just considered a "file" on my computer) or if it's something on my part. The unfortunate thing is that because I'm using Windows, I have to use Unix style paths or it will not work.

**Comment by alekmaul** [comment]
Well, such issue is better on discord to help you quickly.
It seems that the make command is not recognize.
DO you have a msys or something like that environment to do the make command ?

**Comment by Flamethwarrior257** [comment]
Actually, I'm fine now. I tested on Git Bash and it acknowledged what I was looking for.  Thanks for your help. Also, thank you for creating this tool. I'm looking forward to what I'll be making soon.

**Comment by alekmaul** [comment]
ok, great ^^
