### ISSUE TITLE
How can I enter in the discord group?

### ISSUE THREAD

**Issue by odelot** [alekmaul/pvsneslib#281]
I tried with the README.md link but it didn't work. Thanks guys.

**Comment by RetroAntho** [comment]
Welcome back!
The link in the readme seems to works correctly:
https://discord.gg/DzEFnhB
do you used this one?

**Comment by odelot** [comment]
hey @RetroAntho , thank you! It worked

I tried this one, I didnt see the one in the end of the page. 

![image](https://github.com/alekmaul/pvsneslib/assets/5109774/4f3fe1ec-6f22-4389-a654-ddf1d8c91ab3)
