### ISSUE TITLE
Use asar instead of bass

### ISSUE THREAD

**Issue by souldbminersmwc** [alekmaul/pvsneslib#296]
Bass is an outdated assembler. Asar would be better
https://github.com/RPGHacker/asar/

**Comment by alekmaul** [comment]
where do you see we use bass is pvsneslib?

**Comment by RealMalachi** [comment]
The only trace of 🐟 I could find (in current versions of this SDK anyway) was in the readme's special thanks, it seems to be using WLA-DX as its assembler; I'm unfamiliar with the SNES dev scene, but it doesn't seem out of date especially compared to bass

**Comment by alekmaul** [comment]
so I close this issue which is not ... an issue ...
