### ISSUE TITLE
map begin at position 0, 1 instead of 0, 0

### ISSUE THREAD

**Issue by hoit** [alekmaul/pvsneslib#34]
Hello,

We found a small bug in pvsneslib.

When you draw a map, the x position begin to 0 but the y position begin to 1.

To reproduce the issue, you can take the code available here (took from an other issue) :

https://github.com/alekmaul/pvsneslib/files/4206650/Mode0test.zip

I take some print screen to show it. The tileset is like that :

![tileset](https://user-images.githubusercontent.com/981773/78457351-d6971e80-76a9-11ea-9d17-981d01db85e3.png)

The first tile with number "1" is not aligned to 0,0 (It is draw 1 pixel from left and from top)

but when the map is drawn, the tile number "1" is good from left, but has 1 pixel lost from top :
![map](https://user-images.githubusercontent.com/981773/78457403-3988b580-76aa-11ea-8872-4b084b57909a.png)

It produce a gap in some cases with collide. It can be solved easily by doing a scroll just after loading:
bgSetScroll(0,0, -1);

but i think it will be better to solve it.

**Comment by alekmaul** [comment]
Yeah, you're right. I'm doing the scroll only once in my main program in all the games, perhaps I need to add that in all examples ... Another thing in todo list ...

**Comment by hoit** [comment]
do you think it is a bug ? the map should be draw on x = 0, like for y position. For this case, i think it is a bug which could be solved in the library instead of updating sample to have a workaround

**Comment by 1r3n33** [comment]
Hello,
FYI, I have found a technical reason behind the default background y-offset.
From https://wiki.superfamicom.org/backgrounds#toc-3
> Note that many games will set their vertical scroll values to -1 rather than 0. **This is because the SNES loads OBJ data for each scanline during the previous scanline. The very first line, though, wouldn't have any OBJ data loaded! So the SNES doesn't actually output scanline 0, although it does everything to render it**. These games want the first line of their tilemap to be the first line output, so they set their VOFS registers in this manner. Note that an interlace screen needs -2 rather than -1 to properly correct for the missing line 0 (and an emulator would need to add 2 instead of 1 to account for this).

**Comment by hoit** [comment]
Hello,

Thanks, it is really interesting.

So it is not a bug, but i think it should be good to hide this behaviour for everybody by doing bgSetScroll(0,0, -1); (or -2 for interlace screen) in bgInitMapSet function ?

If this modification is not accepted, i will update the wiki page to provide this information somewhere !

**Comment by 1r3n33** [comment]
Hi @hoit,
I am afraid that including a scrolling reset in bgInitMapSet can be a breaking change. For example, I am making a breakout game where blocks are made of background tiles. The blocks can scroll and the tilemap is updated on the fly every collision using bgInitMapSet. It would force me to re-scroll after each collision.
However I consider your suggestion as a reasonable and low-intrusive option that will probably work for most people.
In my humble opinion, the issue comes from user thinking scroll y=0 is actually starting at line 0 (which is not true for some internal technical reasons). It feels like an unexpected behavior. If the goal is to improve user experience why not doing y-1 inside the bgSetScroll? But honestly, I do not like this idea very much.
Updating the documentation to build more awareness on this particularity is certainly a good thing.

**Comment by alekmaul** [comment]
yeah, you're right, I think we need to update the WIKI about that

**Comment by hoit** [comment]
Hi,

Your explanations are clear and i didn't thought about this kind of cases.

I updated the wiki here (the page is not finished but we will keep it in mind like that) : https://github.com/alekmaul/pvsneslib/wiki/Backgrounds
and there : https://github.com/alekmaul/pvsneslib/wiki/Community-FAQ#MapsSection_2

and i think it should be good to update the comment in bgInitMapSet() function for documentation generated with doxygen (but it ask to do a pull request, more heavy...)

Just an other remark about wiki pages owner. It is strange but when i update the page with this account, i appear like "RetroAntho" (RetroAntho edited this page 8 minutes ago · 3 revisions).
I mention both are my accounts and i wanted to remove one but i didn't take the time to finish the clean.
