### ISSUE TITLE
font system seems to work only on 16 color backgrounds

### ISSUE THREAD

**Issue by hoit** [alekmaul/pvsneslib#35]
Hello,

After some tests, the text system provided with pvsneslib seems to work only on 16 colors background.
In all sample where you use text, the mode used is BG_MODE1 which provide 16 colors for bg0 and bg1.

Is it a known constraint ?
If other one are existing, can you provided me ?
(like the 0x0000 address which is used by by the lib to load font but this one is already wrote in the wiki !)

Thanks

**Comment by alekmaul** [comment]
You're right, it is only working in MODE 1. If you want to use it with another mode, you need to develop it.
To be honest, i'm not using the font system because I always have less characters than in a complete system.

**Comment by hoit** [comment]
Ok, i think we can close the issue.

I updated the wiki on 2 pages to forward this information :

https://github.com/alekmaul/pvsneslib/wiki/Community-FAQ#CommonErrorsSection_9

https://github.com/alekmaul/pvsneslib/wiki/Input-and-Output

I think it should be important to update the description on consoleInitText function in consoles.h to provide this information directly in the documentation :

http://www.portabledev.com/pvsneslib/doc/a00404.html#a458fa049800e12429ca0ba401e513746
