### ISSUE TITLE
SRAM problem?

### ISSUE THREAD

**Issue by CristianCG86** [alekmaul/pvsneslib#36]
Hello

I'm trying to save progress into SRAM, but using example project "sram" I can't store anything and the emulators not create the SRAM file.

What's I do wrong?

I'm use consoleCopySram function.

Thanks

**Comment by hoit** [comment]
Hello,

Do you have sample (minimal) code to reproduce your issue or any error message ?

I guess that it is not a compilation issue ? if you get CHECK_HEADERS during build, you have to set parameters in hdr.asm or rebuild the library:
https://github.com/alekmaul/pvsneslib/issues/8

**Comment by CristianCG86** [comment]
I'm trying with sram example project. I compile it, but not works properly.
No, I not get CHECK_HEADERS error during compilation.

**Comment by 1r3n33** [comment]
Hi @CristianCG86,
I have been able to make the 'sram' example works by following @hoit recommendation.
It has required to **change the SRAMSIZE value to $01 in the .SNESHEADER section of hdr.asm files**.

I did this in 2 steps:
1. Modifying the SRAMSIZE value in the [pvsneslib/source/hdr.asm](https://github.com/alekmaul/pvsneslib/blob/master/pvsneslib/source/hdr.asm#L26) file and then rebuild the pvsneslib lib. _If you do not do so, you may get a linker error while building the 'sram' example (CHECK_HEADERS: The object files are from different projects)._
2. Modifying the SRAMSIZE value in the [snes-examples/sram/hdr.asm](https://github.com/alekmaul/pvsneslib/blob/master/snes-examples/sram/hdr.asm#L26) file and then rebuild the 'sram' example.

Hope this helps.

**Comment by alekmaul** [comment]
Hi @CristianCG86 ,
YEs, you're right, you need to do such update to have SRAM example to work (sorry for the lack of newss & help :/).
You must know that the hdr file is shared between SNES lib and your rom file, you can't have something different. But, you can update your right after the compilation with the "snestool" tool, include with pvsneslib.
It is named "$(SNTOOLS)" in each makefile, and if I remember well, you have an option to update your rom to allow SRAM support, even if your hdr file in your project (not in the lib) is not configure to do so (but I need to verify this point).

**Comment by alekmaul** [comment]
as we resolved HEADER issues between lib and examples, I close this issue
