### ISSUE TITLE
How to optimise memory space when loading graphics ?

### ISSUE THREAD

**Issue by hoit** [alekmaul/pvsneslib#37]
Hello,

I need some help to understand how to load resources without losing memory space.

I didn't find a rule that works correctly for all kind of backgrounds (2, 4 & 8bpp) and i would like to optimize space available and gather all resources.
My goal is to find a way to load it without looking in no$sns vram to find adresses and without increment by 0x1000 otherwise i will reach the limit quickly.

If i check the Mode0 sample under graphics folder, everything works correctly when tileset is loaded every 0x1000:

```
	bgInitTileSet(0, &t0, &p0, 0, (&t0_end - &t0), 8, BG_4COLORS0, 0x2000);
	bgInitTileSet(1, &t1, &p1, 0, (&t1_end - &t1), 8, BG_4COLORS0, 0x3000);
	bgInitTileSet(2, &t2, &p2, 0, (&t2_end - &t2), 8, BG_4COLORS0, 0x4000);
	bgInitTileSet(3, &t3, &p3, 0, (&t3_end - &t3), 16, BG_4COLORS0, 0x5000);
```

With no$sns vram, i see that the first tileset finish at 0x2330 and if i try to load the second one on the next line (0x2400), data are overided and the screen is wrong.

If i try to load the first item at 0x2000: (`u16 resources = 0x2000;`)
and the second just after : `resources += (&t0_end - &t0)/2;`

Data are "pasted" but the display is not correct.

The mapset seems to work differently and are loaded every 0x0400 (in Mode0 sample). I also tried to use other adresses without find a rule.

Can you explain me how it works ?

Thanks in advance

**Comment by alekmaul** [comment]
YEs, you can't put what you want for address for every map address.
Take a look here https://wiki.superfamicom.org/working-with-vram-initializing-tiles-and-tile-maps
It must be 0x400 word aligned for each map, sorry about that :/

**Comment by hoit** [comment]
Thank you, the issue is solved with your informations (it is less flexible than i thought), i close it !
