### ISSUE TITLE
linker error when building game likemario 

### ISSUE THREAD

**Issue by lepusagri** [alekmaul/pvsneslib#4]
Hello,
most of the examples can be built now,
but when i try to build the game 'likemario',
my wlalink.exe stop working and crash.

.....
DISCARD: z:/snesdev/pvsneslib/lib/libc.obj:libc_c.asm: Section ".text_0x30" was discarded.
DISCARD: z:/snesdev/pvsneslib/lib/libc.obj:libc_c.asm: Section ".text_"make": *** [/z/snesdev/snes-examples/games/likemario/likemario.sfc] Error 5
rm LikeMario.asm LikeMario.ps

**Comment by alekmaul** [comment]
ok, will check it tomorrow

**Comment by lepusagri** [comment]
i found the problem. i had a different wlalink.exe in my PATH.
(for pure assembler projects)
Sorry.
