### ISSUE TITLE
Changing from background from an another

### ISSUE THREAD

**Issue by KoopintheHub** [alekmaul/pvsneslib#40]
How do I change from a background to an another background? I want to make a title screen for my
puzzle game.

**Comment by hoit** [comment]
Hi, if you want to change your background, i guess that it is a new image (so a new mapset too), you can change it by calling  bgInitTileSet then bgInitMapSet like in graphics sample.

But if your question is about a specific case, you should provide a minimal code to get more help

**Comment by KoopintheHub** [comment]
I done a new image but when I use `bgInitTileSet` then `bgInitMapSet` it gives me a black screen

**Comment by hoit** [comment]
Did you called SetScreenOn function after? 
Is you picture loaded correctly in vram (you can check it in no$sns) ?

Please create a minimal (and buildable) code with only steps needed to reproduce the case, it will be more easy to solve it

**Comment by KoopintheHub** [comment]
It works! Thanks!

**Comment by KoopintheHub** [comment]
Issue closed

**Comment by KoopintheHub** [comment]
Also it was solved by adding setScreenOn(); btw
