### ISSUE TITLE
256 Color bitmap not working

### ISSUE THREAD

**Issue by KoopintheHub** [alekmaul/pvsneslib#41]
I know there was a closed issue in 2018 but it was solved without any help,
I really need help on this but 256 color bitmaps won't work

Error log:
```
data.asm:6: INCBIN_FILE: Overreading file "expand.pic".
data.asm:6: ERROR: Couldn't parse ".incbin".
```

The code in data.asm:
```
.include "hdr.asm"

.section ".rodata2" superfree

dongtiles:
.incbin "expand.pic" skip 0 read 32768

.ends

.section ".rodata3" superfree

dongtiles1:
.incbin "expand.pic" skip 32768 read 6976
dongtiles1_end:

dongmap:
.incbin "expand.map"
dongmap_end:

dongpalette:
.incbin "expand.pal"

.ends

```

Is there a way to solve this? The bitmap is 256 colors and 256x224.

**Comment by alekmaul** [comment]
it is because your bitmap size is not of 32768+6976 bytes 
you need to indicate the size of your bitmap to add it in data.asm.
for example, for a 49540 bytes bitmap, it will be  32768 for 1st bank and (49540-32768) so 16772 for the second one.
the second read will .incbin "expand.pic" skip 32768 read 16772

So, just take a look at your bitmap size to solve your problem.

**Comment by KoopintheHub** [comment]
How do I indicate the size of your bitmap?
(Sorry for the slow reply)

**Comment by alekmaul** [comment]
you must know the size of your bitmap (through explorer, and so on) and you indicate in in data.asm file as I mention in my previous post regarding what you wrote about data.asm file.

**Comment by KoopintheHub** [comment]
Ok, so the bitmap was 58422 bytes so I did 58422-32768 and... same error.
The incbin was now `.incbin "expand.pic" skip 32768 read 25654`

I believe I am not doing it properly.

**Comment by alekmaul** [comment]
if your file is 58422 bytes long, you need to have such data.asm file:

`.include "hdr.asm"

.section ".rodata2" superfree

dongtiles:
.incbin "expand.pic" skip 0 read 32768

.ends

.section ".rodata3" superfree

dongtiles1:
.incbin "expand.pic" skip 32768 read 25654
dongtiles1_end:

dongmap:
.incbin "expand.map"
dongmap_end:

dongpalette:
.incbin "expand.pal"

.ends`

**Comment by KoopintheHub** [comment]
doe not work still!! :(
[Here is the 256 color bitmap](https://bin.smwcentral.net/u/42522/expand.bmp
)

**Comment by 1r3n33** [comment]
Hi @KoopintheHub 
Would you please share the 'expand.pic' file as well? As I understand, this is the size of the .pic (and not .bmp) that should be set in data.asm.
Maybe you can also post the Makefile you're using to generate the .pic?

**Comment by alekmaul** [comment]
Yeah, sorry about the misunderstanding, it is the size of the PIC file, not the bmp file. As you can see, we talk about "expand.pic" in data.asm

**Comment by KoopintheHub** [comment]
Oh I get it! Not Bitmap, .PIC File... I'll check...

**Comment by KoopintheHub** [comment]
So its 50560 bytes on pic
And 50560-32768 = 17792
so `.incbin "expand.pic" skip 32768 read 17792`
And...

OMG IT WORKS!!!!!! WOHOOO! I LOVE PVSNESLIB FOREVER!!!!!
I can do 256 colored bitmaps!!!!! Thanks for the help guys!

*closed
