### ISSUE TITLE
template project doesn't compile

### ISSUE THREAD

**Issue by RedstonekPL** [alekmaul/pvsneslib#43]
I get `Makefile:36: *** empty variable name.  Stop.` when I try to compile (or clean) the template project

here's the makefile snippet
```make
#---------------------------------------------------------------------------------
# list of directories containing libraries, this must be the top level containing
# include and lib
#---------------------------------------------------------------------------------
LIBDIRS	:=	$(PVSNESLIB)
LIBOBJS +:=	.
```

**Comment by alekmaul** [comment]
Why do you have a '.' after LIBOBJS, I do not have it on my template example ?
Try to remove it and clean / compile again.
Also, try to take a look at example, to check if they are compiling on your side.

**Comment by RedstonekPL** [comment]
I put '.', becuase I thought it would work. It didn't with it and it didn't without it.
Same thing happens with the examples.

**Comment by RedstonekPL** [comment]
nvm been using wrong make
