### ISSUE TITLE
shared my port code - may help who is starting

### ISSUE THREAD

**Issue by odelot** [alekmaul/pvsneslib#44]
Hi guys,

I've shared the code of my SoR2 port to Snes using the pvsneslib https://github.com/odelot/sor2_snes 

Maybe you can reuse or study some part of the code. I probably won't work on it anymore, but it may help others.

Cheers

**Comment by alekmaul** [comment]
Thanks a lot, that's great !

**Comment by diegoleao** [comment]
Holy crap, thank you so much! I'm starting to study pvsneslib again, that will certainly help!

**Comment by hoit** [comment]
You can use this one that is interesting too :

https://github.com/1r3n33/bomberworld

**Comment by alekmaul** [comment]
thanks a lot :D !

**Comment by diegoleao** [comment]
> You can use this one that is interesting too :
> https://github.com/1r3n33/bomberworld

All organized in different .c files too, nice!

**Comment by hoit** [comment]
Hello, the idea to share projects is good but using issues is not easy for organisation of the pvsneslib project so we moved it in a specific wiki section to close it here : 

https://github.com/alekmaul/pvsneslib/wiki/Community-code

Feel free to update it if you want :)
