### ISSUE TITLE
Error in example "multiplay5"

### ISSUE THREAD

**Issue by diegoleao** [alekmaul/pvsneslib#45]
I tried to build the "multiplay5" example project, but I get this error:

multiplay5.obj:multiplay5.asm:37: PARSE_STACK: Unresolved reference to "snes_mplay5".
make: *** [C:/snesdev/snes-examples/pads/multiplay5/multiplay5.sfc] Error 1
rm multiplay5.asm multiplay5.ps
(full log in here: [full_log_multiplay5_error.txt](https://github.com/alekmaul/pvsneslib/files/5361174/full_log_multiplay5_error.txt))

I noticed that "extern u8 snes_mplay5;" is present pad.h, but adding this header doesn't help.

Am I doing something wrong? Is this example supposed to work, or is it a WIP?

I'm participating in a game jam (since yesterday) and wanted to include 4-player multiplayer to the rom!

Thank you!

**Comment by alekmaul** [comment]
That is strange as i'm using it for my last game, are you sure you're using the last obj files from the lib ?
Also, try to recompile the lib on your own side, it will be ok ;) !

**Comment by hoit** [comment]
i just tried and it works from my side but i rebuild the library

**Comment by diegoleao** [comment]
Just letting you know that yes, that was the problem :) I went to my pvsneslib path (C:\snesdev\pvsneslib) and built the "pvsneslib.pnproj" project (to those who might have a similar problem).

Thanks!

**Comment by diegoleao** [comment]
For some reason, I can only get joystick 0 input using the multiplay5 project... 
I see the message "USE PADS TO SEE VALUES" (so I know my setup is correct).

Printing the pad0 variable in the loop shows "-1" every time (and the keys for joystick 0 always print a value).

A stream of prints for each player, all pressing KEY_A (jump):
PLAYER -- 0 
COMMAND -- 128 
PLAYER -- 0 [JUMP!!] 
PLAYER -- 1 
COMMAND -- -1 
PLAYER -- 2 
COMMAND -- -1 
PLAYER -- 0 
COMMAND -- 128 
PLAYER -- 0 [JUMP!!] 
PLAYER -- 1 
COMMAND -- -1 
PLAYER -- 2 
COMMAND -- -1

**Comment by alekmaul** [comment]
could you share your code about that ?

**Comment by diegoleao** [comment]
I'm transposing it to the example and will post it in a minute!

**Comment by diegoleao** [comment]
This is the folder with the .sfc rom :
[multiplay5.zip](https://github.com/alekmaul/pvsneslib/files/5362949/multiplay5.zip)

**Comment by diegoleao** [comment]
I made this version to show that I can get joystick 0 and 1 using basically the same code (commenting multi5):
[regular_joystick_test.zip](https://github.com/alekmaul/pvsneslib/files/5362975/regular_joystick_test.zip)

![no multi 5](https://user-images.githubusercontent.com/1707641/95706750-0e20ed80-0c2e-11eb-9ad0-0cfba5b8d9c6.png)

**Comment by RetroAntho** [comment]
It is not updated. Pvsneslib manage now multitap (but this issue could be related to the emulator config) and super scope (which require to be tested!)

**Comment by alekmaul** [comment]
Regarding Superscope, it is not working. I need to add a pool function to populate all variables for multiscope.
wiki updated

**Comment by alekmaul** [comment]
I tested the multi5 example with mesen and it works fine.
