### ISSUE TITLE
What is the correct way to create a tilemap based level

### ISSUE THREAD

**Issue by diegoleao** [alekmaul/pvsneslib#46]
I have so far been able to create single screen levels using pvsneslib, but from I've seen in the examples, the way to create a full level is to create a giant image using exclusively the tiles that fit in vram, is that correct? And the pvsneslib will take care of the rest?

The kind of level that I'm thinking is this:
![image](https://user-images.githubusercontent.com/1707641/95698695-e2473d00-0c18-11eb-8737-414c6138915f.png)

**Comment by alekmaul** [comment]
Helas, no ... Sorry about that but currently PVsneslib is not able to manage large maps. You need to manage that on your own side.

**Comment by diegoleao** [comment]
I see, so let me see if I understand how: I'm thinking I should learn how to load a vertical "strip" of the level to the right, where you can't see it, and everytime you move that way I bring it into the screen (and the same way for the left, up, down), right?

What is the call I should use to do something like that? I can already load sprites piece by piece to vram and show them where I want based on their offset, but for tiles/backgrounds I don't know exactly how to do the same thing.

I'll be studying the sor2 source code further to find a way to do it, but it would be helpful if I know the main "calls" I should be interested in to make this happen.

**Comment by hoit** [comment]
Diegoleao, does the new map engine solve this ticket?

**Comment by diegoleao** [comment]
Yes, if collision also works with the new map engine, then it does!
