### ISSUE TITLE
Sharing my "Sound Test" project - Play BRR, IT, Multiple music files, Mute all sound, and more

### ISSUE THREAD

**Issue by diegoleao** [alekmaul/pvsneslib#48]
Hi! I'm sharing this purely technical project to help others learn how sound works in pvsneslib:
[SoundTest_ByDiegoLeao.zip](https://github.com/alekmaul/pvsneslib/files/5396843/SoundTest_ByDiegoLeao.zip)

@alekmaul I would appreciate if you could eventually check what I wrote in the readme.txt and in source code comments, to check for incorrect information. Even though this project worked for me as a learning tool, I might inadvertently share wrong info.

Contains useful comments from DrLudos' "Keeping Snes Alive" project.

I hope someone finds this useful in the future ;)

**Comment by alekmaul** [comment]
Thanks a lot for sharing code, and your readme is really clear. 
For your information,  smconv.exe gives you the amount of memory you have for 1st .it file and the current .it file when processing them. It is a good way to know if you use too much memory for effects or your musics

**Comment by hoit** [comment]
Hi, thanks for your sample, it is very usefull. It seems to be really complete i will study it in detail.
I already have few questions or remarks about it :)

- The issue with the sound (played with A button) which does not play correctly with music index 3 & 4 is really strange: i guess it is related to to the issue you opened [here](https://github.com/alekmaul/pvsneslib/issues/47) & the section "- Why sometimes the .IT effects sound like blips and pops, or play partially?" in readme ?

- do you think we can play a sound to create a loop during few seconds ?

- not linked to ths sample but in debug, i saw that you did different print functions. I used the same in my project and i did not find a way to override functions with tcc (have the same name with differents parameters). If someone has a solution, please advise me !

- for the future, i do not know if it can be usefull but wla also works with spc700 : it could be an alternative to tasm

**Comment by diegoleao** [comment]
> Hi, thanks for your sample, it is very usefull. It seems to be really complete i will study it in detail.
> I already have few questions or remarks about it :)
> 
> * The issue with the sound (played with A button) which does not play correctly with music index 3 & 4 is really strange: i guess it is related to to the issue you opened [here](https://github.com/alekmaul/pvsneslib/issues/47) & the section "- Why sometimes the .IT effects sound like blips and pops, or play partially?" in readme ?
> * do you think we can play a sound to create a loop during few seconds ?
> * not linked to ths sample but in debug, i saw that you did different print functions. I used the same in my project and i did not find a way to override functions with tcc (have the same name with differents parameters). If someone has a solution, please advise me !
> * for the future, i do not know if it can be usefull but wla also works with spc700 : it could be an alternative to tasm

Hi, glad to see it was useful :)

- Yes, that topic describes exactly the problem with sound effect played with the A button (also B), and it is not so strange after all, the reason is simple: there is not enough memory to load those sound effects. When you play a song, the first thing I do is to spcLoad it to memory. Only after that, I load the sound effects. Since the music in index 3, 4 and 6 are too big; when I load the sound effects, pvsneslib attempt to load them at the next memory position, but there is no memory left. I updated the zip yesterday with detailed math on the subject, maybe you missed the detailed explanation I added later, please re-download the zip and check again.

- Music loops by default, but sound effects won't - and don't I think you should do it like that. It makes way more sense to create a new .it with the sample you want to loop..... and loop it XD Just make a new song in Schism tracker that has a single sample, in loop. But if you really want it, you can just time it and replay the sound, it might work. Use .it sound effects, because you can time it so that it happens just before the end of the previous loop (seamless). Maybe count the number of vblanks (check the counter in the demo). Just be sure to not exceed a soundbank size of around 47732 bytes in total.

- I used different names as well (Print, PrintInt), I don't think you can have the same function name with different parameters.
