### ISSUE TITLE
No graphics in examples, hello_world and sound works

### ISSUE THREAD

**Issue by kernelzeroday** [alekmaul/pvsneslib#5]
Hello, I just grabbed a clone of this repo and i'm encountering some difficulty displaying graphics.

I am able to compile examples with no errors from the compiler or linker, at least none that i can see, but my final SFC files are oonly displaying a black screen when i run them. likemario.sfc plays the background music and the jump sounds, and if I put a quick hello world in the main() function i do see a white line flash before the screen goes black.

I have tried compiling both on windows with msys and linux with wine, using the provided toolset. 

I get this in likemario, and then SimpleSprite and Mode1 examples.

Any suggestions on where to look? Thanks!

**Comment by alekmaul** [comment]
Really strange.
I'm also using WIndows (xp) and msys.
To help me, could you please attached a link to sfc file and also, telling me which emulator you are using.

**Comment by kernelzeroday** [comment]
I did a bit of hunting, I was able to revert to an older commit that built
properly and have been working from there, I will upload a SFC when I get a
chance. I tested the SFC in snes9x, zsnes and higan. I've been working with
a buddy and he did some digging too, I will link him here and see if he can
post some more info.

Thanks!

**Comment by The5heepDev** [comment]
The commit a746a0cbb11a3bbc1af00bf5deff4a1626fabb2e is the base I used to build the examples correctly, as well as my own code. 

Here is a zip of likemario.sfc built with a fresh git pull on windows 10. Building in wine also returns the same output. [likemario.zip](https://github.com/alekmaul/pvsneslib/files/1137822/likemario.zip)

I was actually able to get the backgrounds to display by putting a `setBrightness(0xF)` after the initial `WaitForVBlank(); `, but the sprites still do not show up. The screen scrolls correctly but again, the sprite does not show. When I look at the oam in  no$sns, it seems to be tracing out off the screen.

# <3

**Comment by alekmaul** [comment]
I tested with no$sns and I can see that graphics are here but it seems to be a palette issue.
I also saw that mario sprite is not with visible attribute. Weird.
Currently, try to use this version : http://www.portabledev.com/wiki/doku.php?id=currentversion_en, during the time I need to investigate on code of last commit.

**Comment by kernelzeroday** [comment]
Awesome, thanks for taking a look! If there's anything else that would help
please let us know :D

**Comment by barbarian1987** [comment]
hello
me too i haven"t graphics in "simple sprite" example
i have just added 
oamSetVisible(0,OBJ_SHOW);
in Define sprites paramaters  of the source, and its works
i hope it will help you

**Comment by Scoppio** [comment]
Also having the problem.
Actually I have a few problems.

---

## Setup
 Windows 10
 Msys 1.0.1

## Problem
No graphics from sprites and  etc (but text and color BG showing on music tests)

Make is not working from the downloaded version 2.3.0 (http://www.portabledev.com/wiki/doku.php?id=currentversion_en), when I try to run it I receive the following error
`
    > "make" 
    convert bitmap ... bg0.pic
    /d/snesdev/devkitsnes/tools/gfx2snes -pc4 -n -gs8 -pe0 -po4 -fbmp -m bg0.bmp
    "make": *** [bg0.pic] Error 255
 
    > Process Exit Code: 2
    > Time Taken: 00:31
`

If I download the gfx2snes from source and compile it does run, but with the problem/error that is seen in this thread.

I was able to run everything just fine a few years ago using 2.3.0 on windows 7.

I'll try to compile older versions or fix the code by myself here, but I'd like to hear something about what went wrong.

**Comment by barbarian1987** [comment]
Hello
Alekmaul had said that i will make a new update for the new year to 
resolve this problem
I hope he will found time to do it
Cordially
F.l


Le 2017-12-22 00:58, Lucas Coppio a écrit :

**Comment by anatagawa** [comment]
Windows 10 hate the last gfx2snes :(

And, i have the same problem with black screen.

`setBrightness(0xF);` works , but strange result.

I have a screen with this :
```c
oamInitGfxSet(&monstersprite, (&monstersprite_end-&monstersprite), &monstersprite_pal, (&monstersprite_pal_end-&monstersprite_pal), 0, 0x4000, OBJ_SIZE32);
oamSet(0,  monster.x, monster.y, 3, 0, 0, 0, 0);
oamSetEx(0, OBJ_SMALL, OBJ_SHOW);
oamSetVisible(0, OBJ_SHOW);

setMode(BG_MODE1,0);
bgSetDisable(2);
	
setBrightness(0xF);
```
![Screenshot](http://screens.anatagawa.fr/screen_2018-02-01_22-50-35.png)

but have lot of problems with memory addr

**Comment by alekmaul** [comment]
I will release a new version this week end which fix the graphic issue (I added a new function SetScreenOn). I really like your screen anatagawa ;)

**Comment by alekmaul** [comment]
Available here : https://github.com/alekmaul/pvsneslib/wiki/Download

**Comment by alekmaul** [comment]
Sorry , did a mistake, will still need to work on it

**Comment by alekmaul** [comment]
ok, available now : https://github.com/alekmaul/pvsneslib/wiki/Download
