### ISSUE TITLE
organise code in subfolders

### ISSUE THREAD

**Issue by hoit** [alekmaul/pvsneslib#50]
Hi,

It is not directly related to PVSneslib, but i would like to organise my code in multiple folders.
The current makefile of the project avoid to do it.

To do it, i did some tests on hello world and added a "print" function in files. I have this tree :

Hello_world
Hello_world/hello_world.c
Hello_world/subfolder/other.c
Hello_world/subfolder/other.h

I tried to change in makefile :

```
#SOURCES		:=	.
SOURCES		:=	.*
```
and 
```
#CFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.c)))
CFILES		:=	$(foreach dir,$(SOURCES), $(wildcard $(dir)**/*.c))
```

but i did not find a way to build sources in the root folder **and** in subfolders at the same time!

I do not want to create 1 makefile by subfolder. Some tools (like visual studio) can create virtual directory to organise the code, but i want to keep something independ from technologies

Does someone know how to do it ?

Here is the sample project

[hello_world.zip](https://github.com/alekmaul/pvsneslib/files/5502653/hello_world.zip)

Thanks in advance

**Comment by 1r3n33** [comment]
Hello @hoit,

I faced a similar situation and I resolved the `SOURCES` variable using the following: https://github.com/1r3n33/bomberworld/blob/master/src/Makefile#L14

As you can see, the `SOURCES` variable is set to the current folder `.` plus a shell command `$(shell ls -d */)` that lists all folders in the current folder.
Note that in my case, `CFILES := $(foreach dir,$(SOURCES),$(wildcard $(dir)/*.c))`

This has been tested in Linux bash and does not go beyond the first level of sub-folders.

Hope this can help.

**Comment by hoit** [comment]
Hello @1r3n33 ,

Thank you, it solve my case and i will have better code.
But i would like to improve it again and use many level of sub folders.

I do not understand why it does not work after the 1st level. Is it the reason why you used 1 level or it was enough for your case?

I tried with -R parameter, using grep command, find. Nothing successful for now but if i have the solution, i will keep you informed

**Comment by 1r3n33** [comment]
Hi @hoit,

I have changed my Makefile to use the find command to list all .c files recursively and it seems to work properly.
This should not have depth limitation but I have not thoroughly tested.

See https://github.com/1r3n33/bomberworld/commit/60ba28201ddd3d53938c9aae8059b487c2f44275

**Comment by hoit** [comment]
I understood why the "find" command does not worked yesterday. It returned me : "FIND : parameter format not correct" but it seems to be a conflict between the FIND command of windows (upper case) and the "find" on unix.

With your modifications, i got the same error but it can be solved easily by doing (i do not know if there are better way) :

```
FIND := /c/snesdev/msys/bin/find.exe
CFILES		:=	$(shell $(FIND) $(SOURCES) -type f -name '*.c')
SFILES		:=	$(shell $(FIND) $(SOURCES) -type f -name '*.asm')
```

The program build correctly and seems to work with many subfolders.

Thanks for your help !

**Comment by hoit** [comment]
I close the issue, i hope it will be usefull for other people (and why not for the next version of pvsneslib :) )

**Comment by hoit** [comment]
Hi,
Just a remark for people who will try it. In my case, with a lot of files, i saw that the time to build the project take about 10 seconds more than before.
I think it is related to the « find » command because nothing appear in the output during this time. I did not find a way to solve it but if someone has a solution, please let me know !
