### ISSUE TITLE
how to set cursor position with variables?

### ISSUE THREAD

**Issue by BiberGames** [alekmaul/pvsneslib#51]
Sounds stupid but I've been trying for hours and can't get it to work. Help...

I wanted to move a player across the play area.

The code:

#include <snes.h>

extern char snesfont;
int x = 1;
int y = 1;
char name[32];

strcpy(name,"1");

int main(void) {
	unsigned short pad0;
	consoleInit();
	consoleInitText(0, 0, &snesfont);
	setMode(BG_MODE1,0); bgSetDisable(1); bgSetDisable(2);
	setScreenOn();  
	consoleSetTextCol(RGB15(0,0,31), RGB15(0,0,0));

	strcpy(name,"1");
    consoleDrawText(1,1,"Name of lib=%s",name);
	while(1) {
		// Get current #0 pad
		pad0 = padsCurrent(0);
		if (pad0 & KEY_UP)
		{	
			consoleDrawText(x,y,"A");
		}
		
		WaitForVBlank();
	}
	return 0;
}

**Comment by hoit** [comment]
Hello,

You never update x and y variables, i guess that it is your issue.

**Comment by BiberGames** [comment]
ok

**Comment by alekmaul** [comment]
as it is now clear, i close the issue
