### ISSUE TITLE
Graphics/Sprites/ObjectSize - bug depending the emulator used

### ISSUE THREAD

**Issue by hoit** [alekmaul/pvsneslib#57]
Hi,

The objectSize sample has some glitch with large size on Mesen and on the real hardware.
It seems to work correctly with no$sns and zsnes.

Does someone can help us on it ?

Thanks

**Comment by alekmaul** [comment]
IK'm on it, I will also change definition of each size, it is not correct (we must use <<5 and not mixed with other values like <<6 and <<7), it is confused .

**Comment by alekmaul** [comment]
ok, I fixed it, it was because:
- offset for second sprite was not correct (i fixed it to a generic value)
- update of graphics were done without vblank preservation
