### ISSUE TITLE
Arrays of pointers not working

### ISSUE THREAD

**Issue by mills32** [alekmaul/pvsneslib#58]
Great work updating this!.

I wanted to compile a homebrew with this updated version, and it looks like the arrays of pointers are not working as they did before.

`
//Array of maps
extern char mapb, mapb_end, mapc, mapc_end,...
char *MAP[] = {&mapb,&mapb_end,&mapc,&mapc_end,...};

//Array of music banks
extern char MUSIC_BANK0,MUSIC_BANK1,...};
char *MUSICB[] ={0,&MUSIC_BANK0,&MUSIC_BANK1,...,0x00};
`
When I try to use the arrays, I get nothing (black screen or crash).

`
//Loading music
spcSetBank(MUSICB[1]);
spcAllocateSoundRegion(39);
spcLoad(MUSIC[1]);

//Loading maps
bgInitMapSet(0,MAP[0], ....,...., 0x4000);

`

If I use the pointers alone, they work OK, music and maps are loaded like in the previous version of the library.

Also, function "setBrightness();" is not working... Or is it deprecated?

Thanks.

**Comment by alekmaul** [comment]
You need to declare your pointers as const (and you will not be able to modify them of course). I need to investigate why they are no more working now.
`const char *MAP[] = {&mapb,&mapb_end,&mapc,&mapc_end,...};`
Regarding setBrightness, it is working. What is not working for you with this function ?

**Comment by mills32** [comment]
> 
> 
> You need to declare your pointers as const (and you will not be able to modify them of course). I need to investigate why they are no more working now.
> `const char *MAP[] = {&mapb,&mapb_end,&mapc,&mapc_end,...};`
> Regarding setBrightness, it is working. What is not working for you with this function ?

Thanks!.

I had a fade in-out effect in a demo, and I just used setBrightness(0-15). In this new version It does nothing at all, brightness does not change.

**Comment by alekmaul** [comment]
Regarding setBrightness, I keep this issue open until I can test on my side. Thanks for your reply.

**Comment by hoit** [comment]
Hi,
A lot of changes has been done since this message and i think everything should works with the last release. Can you confirm that you do not have any issue anymore?
If it is not the case, can you provide us a minimal code to show the issue?

**Comment by Ceriole** [comment]
Hello! I've ran into this issue as well. As stated from the "Tips and Tricks" page of the wiki, declaring a `const` array of pointers is done with: `const type* const`. However, it still seems to be mapping the array to RAM. `$7f00000` (WRAM), specifically. I used the .sym file generated by `snes_rules` to check the locations. The animation arrays themselves are being put into ROM as expected. I've tried casting the pointers to other types and using the `&ptr` operator.

This is my code:
```
// Animations
const u8 bug_anim_idle_up[3] = { 0x01, 0x00, ANIM_FRAME(8, 0, 0) }; // In ROM, correctly.
// 7 more...

// Animation table
const u8* const bug_animations[8] = {
  bug_anim_idle_up,
  ...
  bug_anim_walk_right
}; // In WRAM, incorrectly?
```

**Comment by RetroAntho** [comment]
Hello, is it not only `const type*`? i think it is more a typo for the last « const » (missing ponctuation?).
Can you provide a minimal code which can be built? It will be more easy to debug it

**Comment by Ceriole** [comment]
From what I gathered, to make a constant array of constant pointers you need the two `const` keywords. One acting on the type, `u8` and the other modifying the pointer `*`. (From the answer [here](https://stackoverflow.com/a/28320734))

Below is a simplified example of what I'm trying to do.
```#include <snes/snestypes.h>

const u8 anim0[5] = {0x03, 0x02, 0x00, 0x02, 0x04};
const u8 anim1[4] = {0x02, 0x02, 0x06, 0x08};

const u8* const anim_table[2] = { anim0, anim1 };```

**Comment by RetroAntho** [comment]
Ok i did not know that it works like that. The tcc version used to build code on 65c816 miss a lot of functionalities and produce non optimised code. To avoid issues, it is advised to keep code as simple as you can (avoid using struct of array for example). To make const variable, it is done by constify tool (applied on asm file). Maybe it is an improvement to do in this tool.

**Comment by Ceriole** [comment]
Thanks for the help! It does seem to be an issue with constify. For now though, I'll try it a different way.
