### ISSUE TITLE
OamSetVisible bug

### ISSUE THREAD

**Issue by hoit** [alekmaul/pvsneslib#6]
Hello,

When you hide a sprite then display it with oamSetVisible, you need to move it with oamSetXY otherwise the sprite is no more visible on the screen.
To reproduce it, you can try this minimal code:

https://www.petit-fichier.fr/2018/02/28/minimal-code/

I think this example can contains an other bug on text system: if you draw a frame of 8x8px, some letters seems to be tallest than the frame.

**Comment by alekmaul** [comment]
The only way to put a sprite visible or not is to put it outside the screen, so yes, it is normal to use oamSetXY just after to be able to display it again. I don't find a better way to do that, if you have suggestions ...

**Comment by hoit** [comment]
why do you don't keep positions internally before hide sprite ?
maybe it is not efficient for memory or performance reasons, i guess that it is not so easy :)

**Comment by alekmaul** [comment]
Yes, I wanted to have the minimal footprint for the lib, so I didn't want to take care of sprite positions, sorry :/
