### ISSUE TITLE
Issues when compile pvsneslib

### ISSUE THREAD

**Issue by bensuperpc** [alekmaul/pvsneslib#67]
I just tried to compile the program, but it throws me this error :/

```
#10 2.188 Makefile:4: config.mak: No such file or directory
#10 2.189 make: *** No rule to make target 'config.mak'.  Stop.
```

**Comment by hoit** [comment]
It is not pvsneslib but tcc816, right ? You forget to do execute ./configure before which generate this file.

You have few informations on the [wiki](https://github.com/alekmaul/pvsneslib/wiki/Community-FAQ#CommonErrorsSection_10) on it : 

_Go to tcc-65816 directory, then execute ./configure command to create the config.mak file. If you are on windows and get an error like "'.' is not recognized as an internal or external command", you probably need to execute the sh command before. After this command, you can build tcc by doing : make 816-tcc.exe_

If you want, you can also join us on discord to get help

**Comment by bensuperpc** [comment]
Thank you, it's strange, because the docker image builds itself without problem and without ./configure ... now it works ^^
I forked, corrected and updated the docker image, it updates every day: https://github.com/bensuperpc/pvsneslib-docker
