### ISSUE TITLE
building maps and sprite sheet questions

### ISSUE THREAD

**Issue by julianoBRL** [alekmaul/pvsneslib#73]
Hi, these are some doubts I had while testing the examples and codes I was writing, sorry for the number of questions I thought it would be better to put them together instead of creating several issues, could someone help me with this please

what is the best way to make maps/screens? 

Is it possible to use sprite sheets or tilemaps to make maps? 

I have a sprite sheets that are 23KB(256KB if in bmp) and size 512x512 in png with literally everything I will use in the game: text, map blocks, animations, players and enemies. 
is there any way to use this png to build the phases and everything else or do i have to separate everything?
When i try to use it i got the error:
```
data.obj: data.asm: INSERT_SECTIONS: No room for section ".rosprite" (131104 bytes).
make.exe": *** [SimpleSprite.sfc] Error 1
rm data.obj SimpleSprite.asm SimpleSprite.obj hdr.obj SimpleSprite.ps
```

any tips to transform png to bitmap if need be?

is there any way to reduce sprite switching speed on animated sprites?

I'm sorry for the amount of questions it's because it wasn't clear to me while I was reading the wiki.

**Comment by alekmaul** [comment]
you need to use a maximum of 32Kb for each section in data.asm
so , you need to create ".rosprite1" section for example

**Comment by julianoBRL** [comment]
@alekmaul so just for me to confirm, i can have as many sections as i want as long as they don't exceed 32kb?

**Comment by alekmaul** [comment]
of course, no pb with that. As long as you also increase the rom size if it is more that current rom size.

**Comment by RetroAntho** [comment]
hi,

in case of it will be usefull for someone, i add some informations here:

_what is the best way to make maps/screens?

Is it possible to use sprite sheets or tilemaps to make maps?_

to build maps and screen, the best way is to use gfx2snes provided with pvsneslib. If you want to create a map based on tiles file, you will probably need a software like Tiled then write a conversion tool between tiled files format and pvsneslib.

_is there any way to reduce sprite switching speed on animated sprites?_

Yes, you should call the sprite update functions only every X frames. The snes_vblank_count variable will help you to do it : 
https://github.com/alekmaul/pvsneslib/blob/master/snes-examples/timer/timer.c

if you have other questions, feel free to join us on Discord, it will be more easy for us and we will be moer reactiv!
