### ISSUE TITLE
CHECK_HEADERS: The object files are from different projects.

### ISSUE THREAD

**Issue by bigfatbrowncat** [alekmaul/pvsneslib#8]
I'm trying to build "scoring" sample and an error occurs during linkage:

    CHECK_HEADERS: The object files are from different projects.

The facile analysis helps finding that the cause is this option in `hdr.asm`

    SRAMSIZE $01

What should I do to fix or work around this problem? Is this option supported yet?

Thank you!

**Comment by alekmaul** [comment]
yeah, you need to put to$00 because current lib is compiled without sram. Or, just try to compile lib with an hdr.asm file using SRAMSIZE with$01.
