### ISSUE TITLE
Unable to override gravity

### ISSUE THREAD

**Issue by mbh21** [alekmaul/pvsneslib#93]
When using the object and map engine gravity always pulls you to the ground. While this works great for most side-scrollers, this does not work for games where you need left, right, up, and down movements. Examples of games that should not have gravity include:

- Games where your character floats around the screen
- Top-Down RPG style games where you have four directions of movement

**Comment by alekmaul** [comment]
it will be solved in next map engine release (v4.0 of pvsneslib)

**Comment by alekmaul** [comment]
Regarding one object, you can avoid gravity in current engine with no call of CollideMap, UpdateXY functions
