### ISSUE TITLE
Error 5 when trying to use map engine with tileset

### ISSUE THREAD

**Issue by mbh21** [alekmaul/pvsneslib#94]
There are many times when compiling with the map engine and tileset (MakeMapWithTileset) that an **Error 5** is generated when using the `make` command.

**_Consistent errors / Better error message needed:_**

This seems to happen if the tileset does not contain all the tiles listed in the map itself. A better error should be generated in this case.

**_Inconsistent errors:_**

However, there seems to be some bugs related to this as the Error 5 is often inconsistent and seems to come for other reasons too.

Here are two examples on how to reproduce an Error 5 with inconsistency:

**Example 1:**

1. Use the mapandobjects example
2. Resize the bg_L1.png to 2160px or 2152px in width. There is no problem.
3. Reduce it to a size smaller than this such as 2144px in width, an Error 5 is now generated.

**Example 2:**

1. Replacing bg_L1.png with a completely sky blue map that is 512px x 512px gives an Error 5.
2. Replacing bg_L1.png with a completely sky blue map that is 1024px x 672px compiles correctly.

At first I had thought maybe it was because some tiles in the tileset are being removed from the map, but this does not seem to be the case.

Running the gfx2snes command directly fails silently with no error. The command in question is **gfx2snes -pc16 -n -gs8 -pe0 -fpng -m -me -mttileset.png bg_L1.png**

**Comment by RetroAntho** [comment]
As map are now managed by tiled2snes and the part code related to maps have been removed from gfx2snes, i think this issue can be closed.
If i missed something, please let me know !
