### ISSUE TITLE
Map engine does not seem to work for heights larger than 64 tiles

### ISSUE THREAD

**Issue by mbh21** [alekmaul/pvsneslib#95]
Creating a map that is larger than 64 tiles high (8px x 64 tiles = 512px) does not seem to work with map engine.

Steps to reproduce:

1. Using the mapandobjects example as a template create a map that is 1024 x 672 in size (128 tiles wide x 84 tiles high)
2. When the player goes below the 64th tile things get quirky as follows:
   a. Setting bgSetMapPtr 3rd parameter to SC_64x32 collision does not work properly. Either player will fall through blocks that should be solid or empty blocks will appear solid preventing player from going past the 64th block. 
   b. Setting bgSetMapPtr 3rd parameter to SC_64_64 the graphics on the map gets messed up.

**Comment by alekmaul** [comment]
strange, I will check that.

**Comment by alekmaul** [comment]
Do you have source code to help me ?

**Comment by alekmaul** [comment]
Ne need of source code. The new map engine will support maximum of 256 tiles high.
